# CMake generated Testfile for 
# Source directory: E:/GitProiects/DoANTotNghiep/opencv/sources/modules/stitching
# Build directory: E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/stitching
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_stitching "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/bin/opencv_test_stitching.exe" "--gtest_output=xml:opencv_test_stitching.xml")
set_tests_properties(opencv_test_stitching PROPERTIES  LABELS "Main;opencv_stitching;Accuracy" WORKING_DIRECTORY "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/test-reports/accuracy" _BACKTRACE_TRIPLES "E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1309;ocv_add_test_from_target;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1073;ocv_add_accuracy_tests;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/stitching/CMakeLists.txt;11;ocv_define_module;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/stitching/CMakeLists.txt;0;")
add_test(opencv_perf_stitching "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/bin/opencv_perf_stitching.exe" "--gtest_output=xml:opencv_perf_stitching.xml")
set_tests_properties(opencv_perf_stitching PROPERTIES  LABELS "Main;opencv_stitching;Performance" WORKING_DIRECTORY "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/test-reports/performance" _BACKTRACE_TRIPLES "E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1211;ocv_add_test_from_target;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1074;ocv_add_perf_tests;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/stitching/CMakeLists.txt;11;ocv_define_module;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/stitching/CMakeLists.txt;0;")
add_test(opencv_sanity_stitching "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/bin/opencv_perf_stitching.exe" "--gtest_output=xml:opencv_perf_stitching.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_stitching PROPERTIES  LABELS "Main;opencv_stitching;Sanity" WORKING_DIRECTORY "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/test-reports/sanity" _BACKTRACE_TRIPLES "E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1212;ocv_add_test_from_target;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1074;ocv_add_perf_tests;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/stitching/CMakeLists.txt;11;ocv_define_module;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/stitching/CMakeLists.txt;0;")
