# Install script for directory: E:/GitProiects/DoANTotNghiep/opencv/sources/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ade-LICENSE" FILES "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/3rdparty/ade/ade-0.1.1f/LICENSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ffmpeg-license.txt" FILES "E:/GitProiects/DoANTotNghiep/opencv/sources/3rdparty/ffmpeg/license.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ffmpeg-readme.txt" FILES "E:/GitProiects/DoANTotNghiep/opencv/sources/3rdparty/ffmpeg/readme.txt")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/calib3d/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/core/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/dnn/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/features2d/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/flann/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/gapi/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/highgui/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/imgproc/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/java/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/js/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/ml/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/objdetect/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/photo/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/python/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/stitching/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/ts/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/video/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/videoio/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/.firstpass/world/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/core/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/flann/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/imgproc/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/java_bindings_generator/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/ml/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/photo/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/python_tests/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/dnn/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/features2d/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/gapi/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/imgcodecs/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/videoio/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/calib3d/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/highgui/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/objdetect/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/stitching/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/ts/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/video/cmake_install.cmake")
  include("E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/python_bindings_generator/cmake_install.cmake")

endif()

