QT += core gui quick multimedia websockets concurrent network

CONFIG += c++11

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Refer to the documentation for the
# deprecated API to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
        MouseController.cpp \
        PeopleDetectManager.cpp \
        VTIUtility.cpp \
        appengine.cpp \
        dlib-19.19/dlib/all/source.cpp \
        dlib-19.19/dlib/base64/base64_kernel_1.cpp \
        dlib-19.19/dlib/bigint/bigint_kernel_1.cpp \
        dlib-19.19/dlib/bigint/bigint_kernel_2.cpp \
        dlib-19.19/dlib/bit_stream/bit_stream_kernel_1.cpp \
        dlib-19.19/dlib/bsp/bsp.cpp \
        dlib-19.19/dlib/cmake_utils/test_for_avx/avx_test.cpp \
        dlib-19.19/dlib/cmake_utils/test_for_avx/this_file_doesnt_compile.cpp \
        dlib-19.19/dlib/cmake_utils/test_for_cpp11/cpp11_test.cpp \
        dlib-19.19/dlib/cmake_utils/test_for_libjpeg/libjpeg_test.cpp \
        dlib-19.19/dlib/cmake_utils/test_for_libpng/libpng_test.cpp \
        dlib-19.19/dlib/cmake_utils/test_for_neon/neon_test.cpp \
        dlib-19.19/dlib/cmake_utils/test_for_sse4/sse4_test.cpp \
        dlib-19.19/dlib/cmake_utils/test_for_sse4/this_file_doesnt_compile.cpp \
        dlib-19.19/dlib/cuda/cpu_dlib.cpp \
        dlib-19.19/dlib/cuda/cublas_dlibapi.cpp \
        dlib-19.19/dlib/cuda/cuda_data_ptr.cpp \
        dlib-19.19/dlib/cuda/cudnn_dlibapi.cpp \
        dlib-19.19/dlib/cuda/curand_dlibapi.cpp \
        dlib-19.19/dlib/cuda/gpu_data.cpp \
        dlib-19.19/dlib/cuda/tensor_tools.cpp \
        dlib-19.19/dlib/data_io/image_dataset_metadata.cpp \
        dlib-19.19/dlib/data_io/mnist.cpp \
        dlib-19.19/dlib/dir_nav/dir_nav_extensions.cpp \
        dlib-19.19/dlib/dir_nav/dir_nav_kernel_1.cpp \
        dlib-19.19/dlib/dir_nav/dir_nav_kernel_2.cpp \
        dlib-19.19/dlib/entropy_decoder/entropy_decoder_kernel_1.cpp \
        dlib-19.19/dlib/entropy_decoder/entropy_decoder_kernel_2.cpp \
        dlib-19.19/dlib/entropy_encoder/entropy_encoder_kernel_1.cpp \
        dlib-19.19/dlib/entropy_encoder/entropy_encoder_kernel_2.cpp \
        dlib-19.19/dlib/external/cblas/cblas_caxpy.c \
        dlib-19.19/dlib/external/cblas/cblas_ccopy.c \
        dlib-19.19/dlib/external/cblas/cblas_cdotc_sub.c \
        dlib-19.19/dlib/external/cblas/cblas_cdotu_sub.c \
        dlib-19.19/dlib/external/cblas/cblas_cgbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_cgemm.c \
        dlib-19.19/dlib/external/cblas/cblas_cgemv.c \
        dlib-19.19/dlib/external/cblas/cblas_cgerc.c \
        dlib-19.19/dlib/external/cblas/cblas_cgeru.c \
        dlib-19.19/dlib/external/cblas/cblas_chbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_chemm.c \
        dlib-19.19/dlib/external/cblas/cblas_chemv.c \
        dlib-19.19/dlib/external/cblas/cblas_cher.c \
        dlib-19.19/dlib/external/cblas/cblas_cher2.c \
        dlib-19.19/dlib/external/cblas/cblas_cher2k.c \
        dlib-19.19/dlib/external/cblas/cblas_cherk.c \
        dlib-19.19/dlib/external/cblas/cblas_chpmv.c \
        dlib-19.19/dlib/external/cblas/cblas_chpr.c \
        dlib-19.19/dlib/external/cblas/cblas_chpr2.c \
        dlib-19.19/dlib/external/cblas/cblas_cscal.c \
        dlib-19.19/dlib/external/cblas/cblas_csscal.c \
        dlib-19.19/dlib/external/cblas/cblas_cswap.c \
        dlib-19.19/dlib/external/cblas/cblas_csymm.c \
        dlib-19.19/dlib/external/cblas/cblas_csyr2k.c \
        dlib-19.19/dlib/external/cblas/cblas_csyrk.c \
        dlib-19.19/dlib/external/cblas/cblas_ctbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_ctbsv.c \
        dlib-19.19/dlib/external/cblas/cblas_ctpmv.c \
        dlib-19.19/dlib/external/cblas/cblas_ctpsv.c \
        dlib-19.19/dlib/external/cblas/cblas_ctrmm.c \
        dlib-19.19/dlib/external/cblas/cblas_ctrmv.c \
        dlib-19.19/dlib/external/cblas/cblas_ctrsm.c \
        dlib-19.19/dlib/external/cblas/cblas_ctrsv.c \
        dlib-19.19/dlib/external/cblas/cblas_dasum.c \
        dlib-19.19/dlib/external/cblas/cblas_daxpy.c \
        dlib-19.19/dlib/external/cblas/cblas_dcopy.c \
        dlib-19.19/dlib/external/cblas/cblas_ddot.c \
        dlib-19.19/dlib/external/cblas/cblas_dgbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_dgemm.c \
        dlib-19.19/dlib/external/cblas/cblas_dgemv.c \
        dlib-19.19/dlib/external/cblas/cblas_dger.c \
        dlib-19.19/dlib/external/cblas/cblas_dnrm2.c \
        dlib-19.19/dlib/external/cblas/cblas_drot.c \
        dlib-19.19/dlib/external/cblas/cblas_drotg.c \
        dlib-19.19/dlib/external/cblas/cblas_drotm.c \
        dlib-19.19/dlib/external/cblas/cblas_drotmg.c \
        dlib-19.19/dlib/external/cblas/cblas_dsbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_dscal.c \
        dlib-19.19/dlib/external/cblas/cblas_dsdot.c \
        dlib-19.19/dlib/external/cblas/cblas_dspmv.c \
        dlib-19.19/dlib/external/cblas/cblas_dspr.c \
        dlib-19.19/dlib/external/cblas/cblas_dspr2.c \
        dlib-19.19/dlib/external/cblas/cblas_dswap.c \
        dlib-19.19/dlib/external/cblas/cblas_dsymm.c \
        dlib-19.19/dlib/external/cblas/cblas_dsymv.c \
        dlib-19.19/dlib/external/cblas/cblas_dsyr.c \
        dlib-19.19/dlib/external/cblas/cblas_dsyr2.c \
        dlib-19.19/dlib/external/cblas/cblas_dsyr2k.c \
        dlib-19.19/dlib/external/cblas/cblas_dsyrk.c \
        dlib-19.19/dlib/external/cblas/cblas_dtbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_dtbsv.c \
        dlib-19.19/dlib/external/cblas/cblas_dtpmv.c \
        dlib-19.19/dlib/external/cblas/cblas_dtpsv.c \
        dlib-19.19/dlib/external/cblas/cblas_dtrmm.c \
        dlib-19.19/dlib/external/cblas/cblas_dtrmv.c \
        dlib-19.19/dlib/external/cblas/cblas_dtrsm.c \
        dlib-19.19/dlib/external/cblas/cblas_dtrsv.c \
        dlib-19.19/dlib/external/cblas/cblas_dzasum.c \
        dlib-19.19/dlib/external/cblas/cblas_dznrm2.c \
        dlib-19.19/dlib/external/cblas/cblas_icamax.c \
        dlib-19.19/dlib/external/cblas/cblas_idamax.c \
        dlib-19.19/dlib/external/cblas/cblas_isamax.c \
        dlib-19.19/dlib/external/cblas/cblas_izamax.c \
        dlib-19.19/dlib/external/cblas/cblas_sasum.c \
        dlib-19.19/dlib/external/cblas/cblas_saxpy.c \
        dlib-19.19/dlib/external/cblas/cblas_scasum.c \
        dlib-19.19/dlib/external/cblas/cblas_scnrm2.c \
        dlib-19.19/dlib/external/cblas/cblas_scopy.c \
        dlib-19.19/dlib/external/cblas/cblas_sdot.c \
        dlib-19.19/dlib/external/cblas/cblas_sdsdot.c \
        dlib-19.19/dlib/external/cblas/cblas_sgbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_sgemm.c \
        dlib-19.19/dlib/external/cblas/cblas_sgemv.c \
        dlib-19.19/dlib/external/cblas/cblas_sger.c \
        dlib-19.19/dlib/external/cblas/cblas_snrm2.c \
        dlib-19.19/dlib/external/cblas/cblas_srot.c \
        dlib-19.19/dlib/external/cblas/cblas_srotg.c \
        dlib-19.19/dlib/external/cblas/cblas_srotm.c \
        dlib-19.19/dlib/external/cblas/cblas_srotmg.c \
        dlib-19.19/dlib/external/cblas/cblas_ssbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_sscal.c \
        dlib-19.19/dlib/external/cblas/cblas_sspmv.c \
        dlib-19.19/dlib/external/cblas/cblas_sspr.c \
        dlib-19.19/dlib/external/cblas/cblas_sspr2.c \
        dlib-19.19/dlib/external/cblas/cblas_sswap.c \
        dlib-19.19/dlib/external/cblas/cblas_ssymm.c \
        dlib-19.19/dlib/external/cblas/cblas_ssymv.c \
        dlib-19.19/dlib/external/cblas/cblas_ssyr.c \
        dlib-19.19/dlib/external/cblas/cblas_ssyr2.c \
        dlib-19.19/dlib/external/cblas/cblas_ssyr2k.c \
        dlib-19.19/dlib/external/cblas/cblas_ssyrk.c \
        dlib-19.19/dlib/external/cblas/cblas_stbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_stbsv.c \
        dlib-19.19/dlib/external/cblas/cblas_stpmv.c \
        dlib-19.19/dlib/external/cblas/cblas_stpsv.c \
        dlib-19.19/dlib/external/cblas/cblas_strmm.c \
        dlib-19.19/dlib/external/cblas/cblas_strmv.c \
        dlib-19.19/dlib/external/cblas/cblas_strsm.c \
        dlib-19.19/dlib/external/cblas/cblas_strsv.c \
        dlib-19.19/dlib/external/cblas/cblas_xerbla.c \
        dlib-19.19/dlib/external/cblas/cblas_zaxpy.c \
        dlib-19.19/dlib/external/cblas/cblas_zcopy.c \
        dlib-19.19/dlib/external/cblas/cblas_zdotc_sub.c \
        dlib-19.19/dlib/external/cblas/cblas_zdotu_sub.c \
        dlib-19.19/dlib/external/cblas/cblas_zdscal.c \
        dlib-19.19/dlib/external/cblas/cblas_zgbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_zgemm.c \
        dlib-19.19/dlib/external/cblas/cblas_zgemv.c \
        dlib-19.19/dlib/external/cblas/cblas_zgerc.c \
        dlib-19.19/dlib/external/cblas/cblas_zgeru.c \
        dlib-19.19/dlib/external/cblas/cblas_zhbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_zhemm.c \
        dlib-19.19/dlib/external/cblas/cblas_zhemv.c \
        dlib-19.19/dlib/external/cblas/cblas_zher.c \
        dlib-19.19/dlib/external/cblas/cblas_zher2.c \
        dlib-19.19/dlib/external/cblas/cblas_zher2k.c \
        dlib-19.19/dlib/external/cblas/cblas_zherk.c \
        dlib-19.19/dlib/external/cblas/cblas_zhpmv.c \
        dlib-19.19/dlib/external/cblas/cblas_zhpr.c \
        dlib-19.19/dlib/external/cblas/cblas_zhpr2.c \
        dlib-19.19/dlib/external/cblas/cblas_zscal.c \
        dlib-19.19/dlib/external/cblas/cblas_zswap.c \
        dlib-19.19/dlib/external/cblas/cblas_zsymm.c \
        dlib-19.19/dlib/external/cblas/cblas_zsyr2k.c \
        dlib-19.19/dlib/external/cblas/cblas_zsyrk.c \
        dlib-19.19/dlib/external/cblas/cblas_ztbmv.c \
        dlib-19.19/dlib/external/cblas/cblas_ztbsv.c \
        dlib-19.19/dlib/external/cblas/cblas_ztpmv.c \
        dlib-19.19/dlib/external/cblas/cblas_ztpsv.c \
        dlib-19.19/dlib/external/cblas/cblas_ztrmm.c \
        dlib-19.19/dlib/external/cblas/cblas_ztrmv.c \
        dlib-19.19/dlib/external/cblas/cblas_ztrsm.c \
        dlib-19.19/dlib/external/cblas/cblas_ztrsv.c \
        dlib-19.19/dlib/external/libjpeg/jaricom.c \
        dlib-19.19/dlib/external/libjpeg/jcapimin.c \
        dlib-19.19/dlib/external/libjpeg/jcapistd.c \
        dlib-19.19/dlib/external/libjpeg/jcarith.c \
        dlib-19.19/dlib/external/libjpeg/jccoefct.c \
        dlib-19.19/dlib/external/libjpeg/jccolor.c \
        dlib-19.19/dlib/external/libjpeg/jcdctmgr.c \
        dlib-19.19/dlib/external/libjpeg/jchuff.c \
        dlib-19.19/dlib/external/libjpeg/jcinit.c \
        dlib-19.19/dlib/external/libjpeg/jcmainct.c \
        dlib-19.19/dlib/external/libjpeg/jcmarker.c \
        dlib-19.19/dlib/external/libjpeg/jcmaster.c \
        dlib-19.19/dlib/external/libjpeg/jcomapi.c \
        dlib-19.19/dlib/external/libjpeg/jcparam.c \
        dlib-19.19/dlib/external/libjpeg/jcprepct.c \
        dlib-19.19/dlib/external/libjpeg/jcsample.c \
        dlib-19.19/dlib/external/libjpeg/jctrans.c \
        dlib-19.19/dlib/external/libjpeg/jdapimin.c \
        dlib-19.19/dlib/external/libjpeg/jdapistd.c \
        dlib-19.19/dlib/external/libjpeg/jdarith.c \
        dlib-19.19/dlib/external/libjpeg/jdatadst.c \
        dlib-19.19/dlib/external/libjpeg/jdatasrc.c \
        dlib-19.19/dlib/external/libjpeg/jdcoefct.c \
        dlib-19.19/dlib/external/libjpeg/jdcolor.c \
        dlib-19.19/dlib/external/libjpeg/jddctmgr.c \
        dlib-19.19/dlib/external/libjpeg/jdhuff.c \
        dlib-19.19/dlib/external/libjpeg/jdinput.c \
        dlib-19.19/dlib/external/libjpeg/jdmainct.c \
        dlib-19.19/dlib/external/libjpeg/jdmarker.c \
        dlib-19.19/dlib/external/libjpeg/jdmaster.c \
        dlib-19.19/dlib/external/libjpeg/jdmerge.c \
        dlib-19.19/dlib/external/libjpeg/jdpostct.c \
        dlib-19.19/dlib/external/libjpeg/jdsample.c \
        dlib-19.19/dlib/external/libjpeg/jdtrans.c \
        dlib-19.19/dlib/external/libjpeg/jerror.c \
        dlib-19.19/dlib/external/libjpeg/jfdctflt.c \
        dlib-19.19/dlib/external/libjpeg/jfdctfst.c \
        dlib-19.19/dlib/external/libjpeg/jfdctint.c \
        dlib-19.19/dlib/external/libjpeg/jidctflt.c \
        dlib-19.19/dlib/external/libjpeg/jidctfst.c \
        dlib-19.19/dlib/external/libjpeg/jidctint.c \
        dlib-19.19/dlib/external/libjpeg/jmemansi.c \
        dlib-19.19/dlib/external/libjpeg/jmemmgr.c \
        dlib-19.19/dlib/external/libjpeg/jmemname.c \
        dlib-19.19/dlib/external/libjpeg/jmemnobs.c \
        dlib-19.19/dlib/external/libjpeg/jpegtran.c \
        dlib-19.19/dlib/external/libjpeg/jquant1.c \
        dlib-19.19/dlib/external/libjpeg/jquant2.c \
        dlib-19.19/dlib/external/libjpeg/jutils.c \
        dlib-19.19/dlib/external/libjpeg/rdbmp.c \
        dlib-19.19/dlib/external/libjpeg/rdcolmap.c \
        dlib-19.19/dlib/external/libjpeg/rdgif.c \
        dlib-19.19/dlib/external/libjpeg/rdjpgcom.c \
        dlib-19.19/dlib/external/libjpeg/rdppm.c \
        dlib-19.19/dlib/external/libjpeg/rdrle.c \
        dlib-19.19/dlib/external/libjpeg/rdswitch.c \
        dlib-19.19/dlib/external/libjpeg/rdtarga.c \
        dlib-19.19/dlib/external/libjpeg/transupp.c \
        dlib-19.19/dlib/external/libjpeg/wrbmp.c \
        dlib-19.19/dlib/external/libjpeg/wrgif.c \
        dlib-19.19/dlib/external/libjpeg/wrjpgcom.c \
        dlib-19.19/dlib/external/libjpeg/wrppm.c \
        dlib-19.19/dlib/external/libjpeg/wrrle.c \
        dlib-19.19/dlib/external/libjpeg/wrtarga.c \
        dlib-19.19/dlib/external/libpng/arm/arm_init.c \
        dlib-19.19/dlib/external/libpng/arm/filter_neon_intrinsics.c \
        dlib-19.19/dlib/external/libpng/png.c \
        dlib-19.19/dlib/external/libpng/pngerror.c \
        dlib-19.19/dlib/external/libpng/pngget.c \
        dlib-19.19/dlib/external/libpng/pngmem.c \
        dlib-19.19/dlib/external/libpng/pngpread.c \
        dlib-19.19/dlib/external/libpng/pngread.c \
        dlib-19.19/dlib/external/libpng/pngrio.c \
        dlib-19.19/dlib/external/libpng/pngrtran.c \
        dlib-19.19/dlib/external/libpng/pngrutil.c \
        dlib-19.19/dlib/external/libpng/pngset.c \
        dlib-19.19/dlib/external/libpng/pngtrans.c \
        dlib-19.19/dlib/external/libpng/pngwio.c \
        dlib-19.19/dlib/external/libpng/pngwrite.c \
        dlib-19.19/dlib/external/libpng/pngwtran.c \
        dlib-19.19/dlib/external/libpng/pngwutil.c \
        dlib-19.19/dlib/external/zlib/adler32.c \
        dlib-19.19/dlib/external/zlib/compress.c \
        dlib-19.19/dlib/external/zlib/crc32.c \
        dlib-19.19/dlib/external/zlib/deflate.c \
        dlib-19.19/dlib/external/zlib/gzclose.c \
        dlib-19.19/dlib/external/zlib/gzlib.c \
        dlib-19.19/dlib/external/zlib/gzread.c \
        dlib-19.19/dlib/external/zlib/gzwrite.c \
        dlib-19.19/dlib/external/zlib/infback.c \
        dlib-19.19/dlib/external/zlib/inffast.c \
        dlib-19.19/dlib/external/zlib/inflate.c \
        dlib-19.19/dlib/external/zlib/inftrees.c \
        dlib-19.19/dlib/external/zlib/trees.c \
        dlib-19.19/dlib/external/zlib/uncompr.c \
        dlib-19.19/dlib/external/zlib/zutil.c \
        dlib-19.19/dlib/filtering/kalman_filter.cpp \
        dlib-19.19/dlib/global_optimization/global_function_search.cpp \
        dlib-19.19/dlib/gui_core/gui_core_kernel_1.cpp \
        dlib-19.19/dlib/gui_core/gui_core_kernel_2.cpp \
        dlib-19.19/dlib/gui_widgets/base_widgets.cpp \
        dlib-19.19/dlib/gui_widgets/canvas_drawing.cpp \
        dlib-19.19/dlib/gui_widgets/drawable.cpp \
        dlib-19.19/dlib/gui_widgets/fonts.cpp \
        dlib-19.19/dlib/gui_widgets/style.cpp \
        dlib-19.19/dlib/gui_widgets/widgets.cpp \
        dlib-19.19/dlib/http_client/http_client.cpp \
        dlib-19.19/dlib/image_loader/jpeg_loader.cpp \
        dlib-19.19/dlib/image_loader/png_loader.cpp \
        dlib-19.19/dlib/image_saver/save_jpeg.cpp \
        dlib-19.19/dlib/image_saver/save_png.cpp \
        dlib-19.19/dlib/linker/linker_kernel_1.cpp \
        dlib-19.19/dlib/logger/extra_logger_headers.cpp \
        dlib-19.19/dlib/logger/logger_config_file.cpp \
        dlib-19.19/dlib/logger/logger_kernel_1.cpp \
        dlib-19.19/dlib/matlab/example_mex_callback.cpp \
        dlib-19.19/dlib/matlab/example_mex_class.cpp \
        dlib-19.19/dlib/matlab/example_mex_function.cpp \
        dlib-19.19/dlib/matlab/example_mex_struct.cpp \
        dlib-19.19/dlib/matlab/mex_wrapper.cpp \
        dlib-19.19/dlib/matlab/subprocess_stream.cpp \
        dlib-19.19/dlib/md5/md5_kernel_1.cpp \
        dlib-19.19/dlib/misc_api/misc_api_kernel_1.cpp \
        dlib-19.19/dlib/misc_api/misc_api_kernel_2.cpp \
        dlib-19.19/dlib/server/server_http.cpp \
        dlib-19.19/dlib/server/server_iostream.cpp \
        dlib-19.19/dlib/server/server_kernel.cpp \
        dlib-19.19/dlib/sockets/sockets_extensions.cpp \
        dlib-19.19/dlib/sockets/sockets_kernel_1.cpp \
        dlib-19.19/dlib/sockets/sockets_kernel_2.cpp \
        dlib-19.19/dlib/sockstreambuf/sockstreambuf.cpp \
        dlib-19.19/dlib/sockstreambuf/sockstreambuf_unbuffered.cpp \
        dlib-19.19/dlib/stack_trace.cpp \
        dlib-19.19/dlib/svm/auto.cpp \
        dlib-19.19/dlib/test/active_learning.cpp \
        dlib-19.19/dlib/test/any.cpp \
        dlib-19.19/dlib/test/any_function.cpp \
        dlib-19.19/dlib/test/array.cpp \
        dlib-19.19/dlib/test/array2d.cpp \
        dlib-19.19/dlib/test/assignment_learning.cpp \
        dlib-19.19/dlib/test/base64.cpp \
        dlib-19.19/dlib/test/bayes_nets.cpp \
        dlib-19.19/dlib/test/bigint.cpp \
        dlib-19.19/dlib/test/binary_search_tree_kernel_1a.cpp \
        dlib-19.19/dlib/test/binary_search_tree_kernel_2a.cpp \
        dlib-19.19/dlib/test/binary_search_tree_mm1.cpp \
        dlib-19.19/dlib/test/binary_search_tree_mm2.cpp \
        dlib-19.19/dlib/test/blas_bindings/blas_bindings_dot.cpp \
        dlib-19.19/dlib/test/blas_bindings/blas_bindings_gemm.cpp \
        dlib-19.19/dlib/test/blas_bindings/blas_bindings_gemv.cpp \
        dlib-19.19/dlib/test/blas_bindings/blas_bindings_ger.cpp \
        dlib-19.19/dlib/test/blas_bindings/blas_bindings_scal_axpy.cpp \
        dlib-19.19/dlib/test/blas_bindings/vector.cpp \
        dlib-19.19/dlib/test/bridge.cpp \
        dlib-19.19/dlib/test/bsp.cpp \
        dlib-19.19/dlib/test/byte_orderer.cpp \
        dlib-19.19/dlib/test/cca.cpp \
        dlib-19.19/dlib/test/clustering.cpp \
        dlib-19.19/dlib/test/cmd_line_parser.cpp \
        dlib-19.19/dlib/test/cmd_line_parser_wchar_t.cpp \
        dlib-19.19/dlib/test/compress_stream.cpp \
        dlib-19.19/dlib/test/conditioning_class.cpp \
        dlib-19.19/dlib/test/conditioning_class_c.cpp \
        dlib-19.19/dlib/test/config_reader.cpp \
        dlib-19.19/dlib/test/correlation_tracker.cpp \
        dlib-19.19/dlib/test/crc32.cpp \
        dlib-19.19/dlib/test/create_iris_datafile.cpp \
        dlib-19.19/dlib/test/cublas.cpp \
        dlib-19.19/dlib/test/data_io.cpp \
        dlib-19.19/dlib/test/directed_graph.cpp \
        dlib-19.19/dlib/test/discriminant_pca.cpp \
        dlib-19.19/dlib/test/disjoint_subsets.cpp \
        dlib-19.19/dlib/test/disjoint_subsets_sized.cpp \
        dlib-19.19/dlib/test/dnn.cpp \
        dlib-19.19/dlib/test/ekm_and_lisf.cpp \
        dlib-19.19/dlib/test/elastic_net.cpp \
        dlib-19.19/dlib/test/empirical_kernel_map.cpp \
        dlib-19.19/dlib/test/entropy_coder.cpp \
        dlib-19.19/dlib/test/entropy_encoder_model.cpp \
        dlib-19.19/dlib/test/example.cpp \
        dlib-19.19/dlib/test/example_args.cpp \
        dlib-19.19/dlib/test/face.cpp \
        dlib-19.19/dlib/test/fft.cpp \
        dlib-19.19/dlib/test/fhog.cpp \
        dlib-19.19/dlib/test/filtering.cpp \
        dlib-19.19/dlib/test/find_max_factor_graph_nmplp.cpp \
        dlib-19.19/dlib/test/find_max_factor_graph_viterbi.cpp \
        dlib-19.19/dlib/test/find_optimal_parameters.cpp \
        dlib-19.19/dlib/test/geometry.cpp \
        dlib-19.19/dlib/test/global_optimization.cpp \
        dlib-19.19/dlib/test/graph.cpp \
        dlib-19.19/dlib/test/graph_cuts.cpp \
        dlib-19.19/dlib/test/graph_labeler.cpp \
        dlib-19.19/dlib/test/gui/main.cpp \
        dlib-19.19/dlib/test/hash.cpp \
        dlib-19.19/dlib/test/hash_map.cpp \
        dlib-19.19/dlib/test/hash_set.cpp \
        dlib-19.19/dlib/test/hash_table.cpp \
        dlib-19.19/dlib/test/hog_image.cpp \
        dlib-19.19/dlib/test/image.cpp \
        dlib-19.19/dlib/test/iosockstream.cpp \
        dlib-19.19/dlib/test/is_same_object.cpp \
        dlib-19.19/dlib/test/isotonic_regression.cpp \
        dlib-19.19/dlib/test/kcentroid.cpp \
        dlib-19.19/dlib/test/kernel_matrix.cpp \
        dlib-19.19/dlib/test/kmeans.cpp \
        dlib-19.19/dlib/test/learning_to_track.cpp \
        dlib-19.19/dlib/test/least_squares.cpp \
        dlib-19.19/dlib/test/linear_manifold_regularizer.cpp \
        dlib-19.19/dlib/test/lspi.cpp \
        dlib-19.19/dlib/test/lz77_buffer.cpp \
        dlib-19.19/dlib/test/main.cpp \
        dlib-19.19/dlib/test/map.cpp \
        dlib-19.19/dlib/test/matrix.cpp \
        dlib-19.19/dlib/test/matrix2.cpp \
        dlib-19.19/dlib/test/matrix3.cpp \
        dlib-19.19/dlib/test/matrix4.cpp \
        dlib-19.19/dlib/test/matrix_chol.cpp \
        dlib-19.19/dlib/test/matrix_eig.cpp \
        dlib-19.19/dlib/test/matrix_lu.cpp \
        dlib-19.19/dlib/test/matrix_qr.cpp \
        dlib-19.19/dlib/test/max_cost_assignment.cpp \
        dlib-19.19/dlib/test/max_sum_submatrix.cpp \
        dlib-19.19/dlib/test/md5.cpp \
        dlib-19.19/dlib/test/member_function_pointer.cpp \
        dlib-19.19/dlib/test/metaprogramming.cpp \
        dlib-19.19/dlib/test/mpc.cpp \
        dlib-19.19/dlib/test/multithreaded_object.cpp \
        dlib-19.19/dlib/test/numerical_integration.cpp \
        dlib-19.19/dlib/test/object_detector.cpp \
        dlib-19.19/dlib/test/oca.cpp \
        dlib-19.19/dlib/test/one_vs_all_trainer.cpp \
        dlib-19.19/dlib/test/one_vs_one_trainer.cpp \
        dlib-19.19/dlib/test/opt_qp_solver.cpp \
        dlib-19.19/dlib/test/optimization.cpp \
        dlib-19.19/dlib/test/optimization_test_functions.cpp \
        dlib-19.19/dlib/test/parallel_for.cpp \
        dlib-19.19/dlib/test/parse.cpp \
        dlib-19.19/dlib/test/pipe.cpp \
        dlib-19.19/dlib/test/pixel.cpp \
        dlib-19.19/dlib/test/probabilistic.cpp \
        dlib-19.19/dlib/test/pyramid_down.cpp \
        dlib-19.19/dlib/test/queue.cpp \
        dlib-19.19/dlib/test/rand.cpp \
        dlib-19.19/dlib/test/random_forest.cpp \
        dlib-19.19/dlib/test/ranking.cpp \
        dlib-19.19/dlib/test/read_write_mutex.cpp \
        dlib-19.19/dlib/test/reference_counter.cpp \
        dlib-19.19/dlib/test/rls.cpp \
        dlib-19.19/dlib/test/sammon.cpp \
        dlib-19.19/dlib/test/scan_image.cpp \
        dlib-19.19/dlib/test/sequence.cpp \
        dlib-19.19/dlib/test/sequence_labeler.cpp \
        dlib-19.19/dlib/test/sequence_segmenter.cpp \
        dlib-19.19/dlib/test/serialize.cpp \
        dlib-19.19/dlib/test/set.cpp \
        dlib-19.19/dlib/test/sldf.cpp \
        dlib-19.19/dlib/test/sliding_buffer.cpp \
        dlib-19.19/dlib/test/smart_pointers.cpp \
        dlib-19.19/dlib/test/sockets.cpp \
        dlib-19.19/dlib/test/sockets2.cpp \
        dlib-19.19/dlib/test/sockstreambuf.cpp \
        dlib-19.19/dlib/test/sparse_vector.cpp \
        dlib-19.19/dlib/test/stack.cpp \
        dlib-19.19/dlib/test/static_map.cpp \
        dlib-19.19/dlib/test/static_set.cpp \
        dlib-19.19/dlib/test/statistics.cpp \
        dlib-19.19/dlib/test/std_vector_c.cpp \
        dlib-19.19/dlib/test/string.cpp \
        dlib-19.19/dlib/test/svm.cpp \
        dlib-19.19/dlib/test/svm_c_linear.cpp \
        dlib-19.19/dlib/test/svm_c_linear_dcd.cpp \
        dlib-19.19/dlib/test/svm_multiclass_linear.cpp \
        dlib-19.19/dlib/test/svm_struct.cpp \
        dlib-19.19/dlib/test/svr_linear_trainer.cpp \
        dlib-19.19/dlib/test/symmetric_matrix_cache.cpp \
        dlib-19.19/dlib/test/tester.cpp \
        dlib-19.19/dlib/test/thread_pool.cpp \
        dlib-19.19/dlib/test/threads.cpp \
        dlib-19.19/dlib/test/timer.cpp \
        dlib-19.19/dlib/test/tokenizer.cpp \
        dlib-19.19/dlib/test/trust_region.cpp \
        dlib-19.19/dlib/test/tuple.cpp \
        dlib-19.19/dlib/test/type_safe_union.cpp \
        dlib-19.19/dlib/test/vectorstream.cpp \
        dlib-19.19/dlib/test_for_odr_violations.cpp \
        dlib-19.19/dlib/threads/async.cpp \
        dlib-19.19/dlib/threads/multithreaded_object_extension.cpp \
        dlib-19.19/dlib/threads/thread_pool_extension.cpp \
        dlib-19.19/dlib/threads/threaded_object_extension.cpp \
        dlib-19.19/dlib/threads/threads_kernel_1.cpp \
        dlib-19.19/dlib/threads/threads_kernel_2.cpp \
        dlib-19.19/dlib/threads/threads_kernel_shared.cpp \
        dlib-19.19/dlib/timer/timer.cpp \
        dlib-19.19/dlib/tokenizer/tokenizer_kernel_1.cpp \
        dlib-19.19/dlib/unicode/unicode.cpp \
        main.cpp

RESOURCES += qml.qrc

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

HEADERS += \
    ConstDefines.h \
    GlobalTypes.h \
    MouseController.h \
    PeopleDetectManager.h \
    StringDefines.h \
    VTIUtility.h \
    appengine.h \ \
    dlib-19.19/dlib/algs.h \
    dlib-19.19/dlib/any.h \
    dlib-19.19/dlib/any/any.h \
    dlib-19.19/dlib/any/any_abstract.h \
    dlib-19.19/dlib/any/any_decision_function.h \
    dlib-19.19/dlib/any/any_decision_function_abstract.h \
    dlib-19.19/dlib/any/any_function.h \
    dlib-19.19/dlib/any/any_function_abstract.h \
    dlib-19.19/dlib/any/any_function_impl.h \
    dlib-19.19/dlib/any/any_function_impl2.h \
    dlib-19.19/dlib/any/any_trainer.h \
    dlib-19.19/dlib/any/any_trainer_abstract.h \
    dlib-19.19/dlib/array.h \
    dlib-19.19/dlib/array/array_kernel.h \
    dlib-19.19/dlib/array/array_kernel_abstract.h \
    dlib-19.19/dlib/array/array_tools.h \
    dlib-19.19/dlib/array/array_tools_abstract.h \
    dlib-19.19/dlib/array2d.h \
    dlib-19.19/dlib/array2d/array2d_generic_image.h \
    dlib-19.19/dlib/array2d/array2d_kernel.h \
    dlib-19.19/dlib/array2d/array2d_kernel_abstract.h \
    dlib-19.19/dlib/array2d/serialize_pixel_overloads.h \
    dlib-19.19/dlib/assert.h \
    dlib-19.19/dlib/base64.h \
    dlib-19.19/dlib/base64/base64_kernel_1.h \
    dlib-19.19/dlib/base64/base64_kernel_abstract.h \
    dlib-19.19/dlib/bayes_utils.h \
    dlib-19.19/dlib/bayes_utils/bayes_utils.h \
    dlib-19.19/dlib/bayes_utils/bayes_utils_abstract.h \
    dlib-19.19/dlib/bigint.h \
    dlib-19.19/dlib/bigint/bigint_kernel_1.h \
    dlib-19.19/dlib/bigint/bigint_kernel_2.h \
    dlib-19.19/dlib/bigint/bigint_kernel_abstract.h \
    dlib-19.19/dlib/bigint/bigint_kernel_c.h \
    dlib-19.19/dlib/binary_search_tree.h \
    dlib-19.19/dlib/binary_search_tree/binary_search_tree_kernel_1.h \
    dlib-19.19/dlib/binary_search_tree/binary_search_tree_kernel_2.h \
    dlib-19.19/dlib/binary_search_tree/binary_search_tree_kernel_abstract.h \
    dlib-19.19/dlib/binary_search_tree/binary_search_tree_kernel_c.h \
    dlib-19.19/dlib/bit_stream.h \
    dlib-19.19/dlib/bit_stream/bit_stream_kernel_1.h \
    dlib-19.19/dlib/bit_stream/bit_stream_kernel_abstract.h \
    dlib-19.19/dlib/bit_stream/bit_stream_kernel_c.h \
    dlib-19.19/dlib/bit_stream/bit_stream_multi_1.h \
    dlib-19.19/dlib/bit_stream/bit_stream_multi_abstract.h \
    dlib-19.19/dlib/bit_stream/bit_stream_multi_c.h \
    dlib-19.19/dlib/bits/c++config.h \
    dlib-19.19/dlib/bound_function_pointer.h \
    dlib-19.19/dlib/bound_function_pointer/bound_function_pointer_kernel_1.h \
    dlib-19.19/dlib/bound_function_pointer/bound_function_pointer_kernel_abstract.h \
    dlib-19.19/dlib/bridge.h \
    dlib-19.19/dlib/bridge/bridge.h \
    dlib-19.19/dlib/bridge/bridge_abstract.h \
    dlib-19.19/dlib/bsp.h \
    dlib-19.19/dlib/bsp/bsp.h \
    dlib-19.19/dlib/bsp/bsp_abstract.h \
    dlib-19.19/dlib/byte_orderer.h \
    dlib-19.19/dlib/byte_orderer/byte_orderer_kernel_1.h \
    dlib-19.19/dlib/byte_orderer/byte_orderer_kernel_abstract.h \
    dlib-19.19/dlib/cassert \
    dlib-19.19/dlib/clustering.h \
    dlib-19.19/dlib/clustering/bottom_up_cluster.h \
    dlib-19.19/dlib/clustering/bottom_up_cluster_abstract.h \
    dlib-19.19/dlib/clustering/chinese_whispers.h \
    dlib-19.19/dlib/clustering/chinese_whispers_abstract.h \
    dlib-19.19/dlib/clustering/modularity_clustering.h \
    dlib-19.19/dlib/clustering/modularity_clustering_abstract.h \
    dlib-19.19/dlib/clustering/spectral_cluster.h \
    dlib-19.19/dlib/clustering/spectral_cluster_abstract.h \
    dlib-19.19/dlib/cmd_line_parser.h \
    dlib-19.19/dlib/cmd_line_parser/cmd_line_parser_check_1.h \
    dlib-19.19/dlib/cmd_line_parser/cmd_line_parser_check_c.h \
    dlib-19.19/dlib/cmd_line_parser/cmd_line_parser_kernel_1.h \
    dlib-19.19/dlib/cmd_line_parser/cmd_line_parser_kernel_abstract.h \
    dlib-19.19/dlib/cmd_line_parser/cmd_line_parser_kernel_c.h \
    dlib-19.19/dlib/cmd_line_parser/cmd_line_parser_print_1.h \
    dlib-19.19/dlib/cmd_line_parser/get_option.h \
    dlib-19.19/dlib/cmd_line_parser/get_option_abstract.h \
    dlib-19.19/dlib/compress_stream.h \
    dlib-19.19/dlib/compress_stream/compress_stream_kernel_1.h \
    dlib-19.19/dlib/compress_stream/compress_stream_kernel_2.h \
    dlib-19.19/dlib/compress_stream/compress_stream_kernel_3.h \
    dlib-19.19/dlib/compress_stream/compress_stream_kernel_abstract.h \
    dlib-19.19/dlib/conditioning_class.h \
    dlib-19.19/dlib/conditioning_class/conditioning_class_kernel_1.h \
    dlib-19.19/dlib/conditioning_class/conditioning_class_kernel_2.h \
    dlib-19.19/dlib/conditioning_class/conditioning_class_kernel_3.h \
    dlib-19.19/dlib/conditioning_class/conditioning_class_kernel_4.h \
    dlib-19.19/dlib/conditioning_class/conditioning_class_kernel_abstract.h \
    dlib-19.19/dlib/conditioning_class/conditioning_class_kernel_c.h \
    dlib-19.19/dlib/config.h \
    dlib-19.19/dlib/config_reader.h \
    dlib-19.19/dlib/config_reader/config_reader_kernel_1.h \
    dlib-19.19/dlib/config_reader/config_reader_kernel_abstract.h \
    dlib-19.19/dlib/config_reader/config_reader_thread_safe_1.h \
    dlib-19.19/dlib/config_reader/config_reader_thread_safe_abstract.h \
    dlib-19.19/dlib/console_progress_indicator.h \
    dlib-19.19/dlib/control.h \
    dlib-19.19/dlib/control/approximate_linear_models.h \
    dlib-19.19/dlib/control/approximate_linear_models_abstract.h \
    dlib-19.19/dlib/control/lspi.h \
    dlib-19.19/dlib/control/lspi_abstract.h \
    dlib-19.19/dlib/control/mpc.h \
    dlib-19.19/dlib/control/mpc_abstract.h \
    dlib-19.19/dlib/cpp_pretty_printer.h \
    dlib-19.19/dlib/cpp_pretty_printer/cpp_pretty_printer_kernel_1.h \
    dlib-19.19/dlib/cpp_pretty_printer/cpp_pretty_printer_kernel_2.h \
    dlib-19.19/dlib/cpp_pretty_printer/cpp_pretty_printer_kernel_abstract.h \
    dlib-19.19/dlib/cpp_tokenizer.h \
    dlib-19.19/dlib/cpp_tokenizer/cpp_tokenizer_kernel_1.h \
    dlib-19.19/dlib/cpp_tokenizer/cpp_tokenizer_kernel_abstract.h \
    dlib-19.19/dlib/cpp_tokenizer/cpp_tokenizer_kernel_c.h \
    dlib-19.19/dlib/crc32.h \
    dlib-19.19/dlib/crc32/crc32_kernel_1.h \
    dlib-19.19/dlib/crc32/crc32_kernel_abstract.h \
    dlib-19.19/dlib/cstring \
    dlib-19.19/dlib/cuda/cpu_dlib.h \
    dlib-19.19/dlib/cuda/cublas_dlibapi.h \
    dlib-19.19/dlib/cuda/cuda_data_ptr.h \
    dlib-19.19/dlib/cuda/cuda_dlib.h \
    dlib-19.19/dlib/cuda/cuda_errors.h \
    dlib-19.19/dlib/cuda/cuda_utils.h \
    dlib-19.19/dlib/cuda/cudnn_dlibapi.h \
    dlib-19.19/dlib/cuda/curand_dlibapi.h \
    dlib-19.19/dlib/cuda/cusolver_dlibapi.h \
    dlib-19.19/dlib/cuda/gpu_data.h \
    dlib-19.19/dlib/cuda/gpu_data_abstract.h \
    dlib-19.19/dlib/cuda/tensor.h \
    dlib-19.19/dlib/cuda/tensor_abstract.h \
    dlib-19.19/dlib/cuda/tensor_tools.h \
    dlib-19.19/dlib/data_io.h \
    dlib-19.19/dlib/data_io/image_dataset_metadata.h \
    dlib-19.19/dlib/data_io/libsvm_io.h \
    dlib-19.19/dlib/data_io/libsvm_io_abstract.h \
    dlib-19.19/dlib/data_io/load_image_dataset.h \
    dlib-19.19/dlib/data_io/load_image_dataset_abstract.h \
    dlib-19.19/dlib/data_io/mnist.h \
    dlib-19.19/dlib/data_io/mnist_abstract.h \
    dlib-19.19/dlib/dir_nav.h \
    dlib-19.19/dlib/dir_nav/dir_nav_extensions.h \
    dlib-19.19/dlib/dir_nav/dir_nav_extensions_abstract.h \
    dlib-19.19/dlib/dir_nav/dir_nav_kernel_1.h \
    dlib-19.19/dlib/dir_nav/dir_nav_kernel_2.h \
    dlib-19.19/dlib/dir_nav/dir_nav_kernel_abstract.h \
    dlib-19.19/dlib/dir_nav/posix.h \
    dlib-19.19/dlib/dir_nav/windows.h \
    dlib-19.19/dlib/directed_graph.h \
    dlib-19.19/dlib/directed_graph/directed_graph_kernel_1.h \
    dlib-19.19/dlib/directed_graph/directed_graph_kernel_abstract.h \
    dlib-19.19/dlib/disjoint_subsets.h \
    dlib-19.19/dlib/disjoint_subsets/disjoint_subsets.h \
    dlib-19.19/dlib/disjoint_subsets/disjoint_subsets_abstract.h \
    dlib-19.19/dlib/disjoint_subsets/disjoint_subsets_sized.h \
    dlib-19.19/dlib/disjoint_subsets/disjoint_subsets_sized_abstract.h \
    dlib-19.19/dlib/dnn.h \
    dlib-19.19/dlib/dnn/core.h \
    dlib-19.19/dlib/dnn/core_abstract.h \
    dlib-19.19/dlib/dnn/input.h \
    dlib-19.19/dlib/dnn/input_abstract.h \
    dlib-19.19/dlib/dnn/layers.h \
    dlib-19.19/dlib/dnn/layers_abstract.h \
    dlib-19.19/dlib/dnn/loss.h \
    dlib-19.19/dlib/dnn/loss_abstract.h \
    dlib-19.19/dlib/dnn/solvers.h \
    dlib-19.19/dlib/dnn/solvers_abstract.h \
    dlib-19.19/dlib/dnn/trainer.h \
    dlib-19.19/dlib/dnn/trainer_abstract.h \
    dlib-19.19/dlib/dnn/utilities.h \
    dlib-19.19/dlib/dnn/utilities_abstract.h \
    dlib-19.19/dlib/dnn/validation.h \
    dlib-19.19/dlib/enable_if.h \
    dlib-19.19/dlib/entropy_decoder.h \
    dlib-19.19/dlib/entropy_decoder/entropy_decoder_kernel_1.h \
    dlib-19.19/dlib/entropy_decoder/entropy_decoder_kernel_2.h \
    dlib-19.19/dlib/entropy_decoder/entropy_decoder_kernel_abstract.h \
    dlib-19.19/dlib/entropy_decoder/entropy_decoder_kernel_c.h \
    dlib-19.19/dlib/entropy_decoder_model.h \
    dlib-19.19/dlib/entropy_decoder_model/entropy_decoder_model_kernel_1.h \
    dlib-19.19/dlib/entropy_decoder_model/entropy_decoder_model_kernel_2.h \
    dlib-19.19/dlib/entropy_decoder_model/entropy_decoder_model_kernel_3.h \
    dlib-19.19/dlib/entropy_decoder_model/entropy_decoder_model_kernel_4.h \
    dlib-19.19/dlib/entropy_decoder_model/entropy_decoder_model_kernel_5.h \
    dlib-19.19/dlib/entropy_decoder_model/entropy_decoder_model_kernel_6.h \
    dlib-19.19/dlib/entropy_decoder_model/entropy_decoder_model_kernel_abstract.h \
    dlib-19.19/dlib/entropy_encoder.h \
    dlib-19.19/dlib/entropy_encoder/entropy_encoder_kernel_1.h \
    dlib-19.19/dlib/entropy_encoder/entropy_encoder_kernel_2.h \
    dlib-19.19/dlib/entropy_encoder/entropy_encoder_kernel_abstract.h \
    dlib-19.19/dlib/entropy_encoder/entropy_encoder_kernel_c.h \
    dlib-19.19/dlib/entropy_encoder_model.h \
    dlib-19.19/dlib/entropy_encoder_model/entropy_encoder_model_kernel_1.h \
    dlib-19.19/dlib/entropy_encoder_model/entropy_encoder_model_kernel_2.h \
    dlib-19.19/dlib/entropy_encoder_model/entropy_encoder_model_kernel_3.h \
    dlib-19.19/dlib/entropy_encoder_model/entropy_encoder_model_kernel_4.h \
    dlib-19.19/dlib/entropy_encoder_model/entropy_encoder_model_kernel_5.h \
    dlib-19.19/dlib/entropy_encoder_model/entropy_encoder_model_kernel_6.h \
    dlib-19.19/dlib/entropy_encoder_model/entropy_encoder_model_kernel_abstract.h \
    dlib-19.19/dlib/entropy_encoder_model/entropy_encoder_model_kernel_c.h \
    dlib-19.19/dlib/error.h \
    dlib-19.19/dlib/external/cblas/cblas.h \
    dlib-19.19/dlib/external/cblas/cblas_f77.h \
    dlib-19.19/dlib/external/libjpeg/cderror.h \
    dlib-19.19/dlib/external/libjpeg/cdjpeg.h \
    dlib-19.19/dlib/external/libjpeg/jconfig.h \
    dlib-19.19/dlib/external/libjpeg/jdct.h \
    dlib-19.19/dlib/external/libjpeg/jerror.h \
    dlib-19.19/dlib/external/libjpeg/jinclude.h \
    dlib-19.19/dlib/external/libjpeg/jmemsys.h \
    dlib-19.19/dlib/external/libjpeg/jmorecfg.h \
    dlib-19.19/dlib/external/libjpeg/jpegint.h \
    dlib-19.19/dlib/external/libjpeg/jpeglib.h \
    dlib-19.19/dlib/external/libjpeg/jversion.h \
    dlib-19.19/dlib/external/libjpeg/transupp.h \
    dlib-19.19/dlib/external/libpng/arm/filter_neon.S \
    dlib-19.19/dlib/external/libpng/png.h \
    dlib-19.19/dlib/external/libpng/pngconf.h \
    dlib-19.19/dlib/external/libpng/pngdebug.h \
    dlib-19.19/dlib/external/libpng/pnginfo.h \
    dlib-19.19/dlib/external/libpng/pnglibconf.h \
    dlib-19.19/dlib/external/libpng/pngpriv.h \
    dlib-19.19/dlib/external/libpng/pngstruct.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/attr.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/buffer_info.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/cast.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/chrono.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/common.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/complex.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/detail/class.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/detail/common.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/detail/descr.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/detail/init.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/detail/internals.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/detail/typeid.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/eigen.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/embed.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/eval.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/functional.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/iostream.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/numpy.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/operators.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/options.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/pybind11.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/pytypes.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/stl.h \
    dlib-19.19/dlib/external/pybind11/include/pybind11/stl_bind.h \
    dlib-19.19/dlib/external/zlib/crc32.h \
    dlib-19.19/dlib/external/zlib/deflate.h \
    dlib-19.19/dlib/external/zlib/gzguts.h \
    dlib-19.19/dlib/external/zlib/inffast.h \
    dlib-19.19/dlib/external/zlib/inffixed.h \
    dlib-19.19/dlib/external/zlib/inflate.h \
    dlib-19.19/dlib/external/zlib/inftrees.h \
    dlib-19.19/dlib/external/zlib/trees.h \
    dlib-19.19/dlib/external/zlib/zconf.h \
    dlib-19.19/dlib/external/zlib/zlib.h \
    dlib-19.19/dlib/external/zlib/zutil.h \
    dlib-19.19/dlib/filtering.h \
    dlib-19.19/dlib/filtering/kalman_filter.h \
    dlib-19.19/dlib/filtering/kalman_filter_abstract.h \
    dlib-19.19/dlib/filtering/rls_filter.h \
    dlib-19.19/dlib/filtering/rls_filter_abstract.h \
    dlib-19.19/dlib/float_details.h \
    dlib-19.19/dlib/fstream \
    dlib-19.19/dlib/general_hash/count_bits.h \
    dlib-19.19/dlib/general_hash/count_bits_abstract.h \
    dlib-19.19/dlib/general_hash/general_hash.h \
    dlib-19.19/dlib/general_hash/hash.h \
    dlib-19.19/dlib/general_hash/hash_abstract.h \
    dlib-19.19/dlib/general_hash/murmur_hash3.h \
    dlib-19.19/dlib/general_hash/murmur_hash3_abstract.h \
    dlib-19.19/dlib/general_hash/random_hashing.h \
    dlib-19.19/dlib/general_hash/random_hashing_abstract.h \
    dlib-19.19/dlib/geometry.h \
    dlib-19.19/dlib/geometry/border_enumerator.h \
    dlib-19.19/dlib/geometry/border_enumerator_abstract.h \
    dlib-19.19/dlib/geometry/drectangle.h \
    dlib-19.19/dlib/geometry/drectangle_abstract.h \
    dlib-19.19/dlib/geometry/line.h \
    dlib-19.19/dlib/geometry/line_abstract.h \
    dlib-19.19/dlib/geometry/point_transforms.h \
    dlib-19.19/dlib/geometry/point_transforms_abstract.h \
    dlib-19.19/dlib/geometry/rectangle.h \
    dlib-19.19/dlib/geometry/rectangle_abstract.h \
    dlib-19.19/dlib/geometry/vector.h \
    dlib-19.19/dlib/geometry/vector_abstract.h \
    dlib-19.19/dlib/global_optimization.h \
    dlib-19.19/dlib/global_optimization/find_max_global.h \
    dlib-19.19/dlib/global_optimization/find_max_global_abstract.h \
    dlib-19.19/dlib/global_optimization/global_function_search.h \
    dlib-19.19/dlib/global_optimization/global_function_search_abstract.h \
    dlib-19.19/dlib/global_optimization/upper_bound_function.h \
    dlib-19.19/dlib/global_optimization/upper_bound_function_abstract.h \
    dlib-19.19/dlib/graph.h \
    dlib-19.19/dlib/graph/graph_kernel_1.h \
    dlib-19.19/dlib/graph/graph_kernel_abstract.h \
    dlib-19.19/dlib/graph_cuts.h \
    dlib-19.19/dlib/graph_cuts/find_max_factor_graph_potts.h \
    dlib-19.19/dlib/graph_cuts/find_max_factor_graph_potts_abstract.h \
    dlib-19.19/dlib/graph_cuts/general_flow_graph.h \
    dlib-19.19/dlib/graph_cuts/general_potts_problem.h \
    dlib-19.19/dlib/graph_cuts/graph_labeler.h \
    dlib-19.19/dlib/graph_cuts/graph_labeler_abstract.h \
    dlib-19.19/dlib/graph_cuts/min_cut.h \
    dlib-19.19/dlib/graph_cuts/min_cut_abstract.h \
    dlib-19.19/dlib/graph_utils.h \
    dlib-19.19/dlib/graph_utils/edge_list_graphs.h \
    dlib-19.19/dlib/graph_utils/edge_list_graphs_abstract.h \
    dlib-19.19/dlib/graph_utils/find_k_nearest_neighbors_lsh.h \
    dlib-19.19/dlib/graph_utils/find_k_nearest_neighbors_lsh_abstract.h \
    dlib-19.19/dlib/graph_utils/function_objects.h \
    dlib-19.19/dlib/graph_utils/function_objects_abstract.h \
    dlib-19.19/dlib/graph_utils/graph_utils.h \
    dlib-19.19/dlib/graph_utils/graph_utils_abstract.h \
    dlib-19.19/dlib/graph_utils/ordered_sample_pair.h \
    dlib-19.19/dlib/graph_utils/ordered_sample_pair_abstract.h \
    dlib-19.19/dlib/graph_utils/sample_pair.h \
    dlib-19.19/dlib/graph_utils/sample_pair_abstract.h \
    dlib-19.19/dlib/graph_utils_threaded.h \
    dlib-19.19/dlib/gui_core.h \
    dlib-19.19/dlib/gui_core/gui_core_kernel_1.h \
    dlib-19.19/dlib/gui_core/gui_core_kernel_2.h \
    dlib-19.19/dlib/gui_core/gui_core_kernel_abstract.h \
    dlib-19.19/dlib/gui_core/windows.h \
    dlib-19.19/dlib/gui_core/xlib.h \
    dlib-19.19/dlib/gui_widgets.h \
    dlib-19.19/dlib/gui_widgets/base_widgets.h \
    dlib-19.19/dlib/gui_widgets/base_widgets_abstract.h \
    dlib-19.19/dlib/gui_widgets/canvas_drawing.h \
    dlib-19.19/dlib/gui_widgets/canvas_drawing_abstract.h \
    dlib-19.19/dlib/gui_widgets/drawable.h \
    dlib-19.19/dlib/gui_widgets/drawable_abstract.h \
    dlib-19.19/dlib/gui_widgets/fonts.h \
    dlib-19.19/dlib/gui_widgets/fonts_abstract.h \
    dlib-19.19/dlib/gui_widgets/nativefont.h \
    dlib-19.19/dlib/gui_widgets/style.h \
    dlib-19.19/dlib/gui_widgets/style_abstract.h \
    dlib-19.19/dlib/gui_widgets/widgets.h \
    dlib-19.19/dlib/gui_widgets/widgets_abstract.h \
    dlib-19.19/dlib/hash.h \
    dlib-19.19/dlib/hash_map.h \
    dlib-19.19/dlib/hash_map/hash_map_kernel_1.h \
    dlib-19.19/dlib/hash_map/hash_map_kernel_abstract.h \
    dlib-19.19/dlib/hash_map/hash_map_kernel_c.h \
    dlib-19.19/dlib/hash_set.h \
    dlib-19.19/dlib/hash_set/hash_set_kernel_1.h \
    dlib-19.19/dlib/hash_set/hash_set_kernel_abstract.h \
    dlib-19.19/dlib/hash_set/hash_set_kernel_c.h \
    dlib-19.19/dlib/hash_table.h \
    dlib-19.19/dlib/hash_table/hash_table_kernel_1.h \
    dlib-19.19/dlib/hash_table/hash_table_kernel_2.h \
    dlib-19.19/dlib/hash_table/hash_table_kernel_abstract.h \
    dlib-19.19/dlib/hash_table/hash_table_kernel_c.h \
    dlib-19.19/dlib/http_client/http_client.h \
    dlib-19.19/dlib/http_client/http_client_abstract.h \
    dlib-19.19/dlib/image_io.h \
    dlib-19.19/dlib/image_keypoint.h \
    dlib-19.19/dlib/image_keypoint/binned_vector_feature_image.h \
    dlib-19.19/dlib/image_keypoint/binned_vector_feature_image_abstract.h \
    dlib-19.19/dlib/image_keypoint/build_separable_poly_filters.h \
    dlib-19.19/dlib/image_keypoint/draw_surf_points.h \
    dlib-19.19/dlib/image_keypoint/draw_surf_points_abstract.h \
    dlib-19.19/dlib/image_keypoint/fine_hog_image.h \
    dlib-19.19/dlib/image_keypoint/fine_hog_image_abstract.h \
    dlib-19.19/dlib/image_keypoint/hashed_feature_image.h \
    dlib-19.19/dlib/image_keypoint/hashed_feature_image_abstract.h \
    dlib-19.19/dlib/image_keypoint/hessian_pyramid.h \
    dlib-19.19/dlib/image_keypoint/hessian_pyramid_abstract.h \
    dlib-19.19/dlib/image_keypoint/hog.h \
    dlib-19.19/dlib/image_keypoint/hog_abstract.h \
    dlib-19.19/dlib/image_keypoint/nearest_neighbor_feature_image.h \
    dlib-19.19/dlib/image_keypoint/nearest_neighbor_feature_image_abstract.h \
    dlib-19.19/dlib/image_keypoint/poly_image.h \
    dlib-19.19/dlib/image_keypoint/poly_image_abstract.h \
    dlib-19.19/dlib/image_keypoint/surf.h \
    dlib-19.19/dlib/image_keypoint/surf_abstract.h \
    dlib-19.19/dlib/image_loader/image_loader.h \
    dlib-19.19/dlib/image_loader/image_loader_abstract.h \
    dlib-19.19/dlib/image_loader/jpeg_loader.h \
    dlib-19.19/dlib/image_loader/jpeg_loader_abstract.h \
    dlib-19.19/dlib/image_loader/load_image.h \
    dlib-19.19/dlib/image_loader/load_image_abstract.h \
    dlib-19.19/dlib/image_loader/png_loader.h \
    dlib-19.19/dlib/image_loader/png_loader_abstract.h \
    dlib-19.19/dlib/image_processing.h \
    dlib-19.19/dlib/image_processing/box_overlap_testing.h \
    dlib-19.19/dlib/image_processing/box_overlap_testing_abstract.h \
    dlib-19.19/dlib/image_processing/correlation_tracker.h \
    dlib-19.19/dlib/image_processing/correlation_tracker_abstract.h \
    dlib-19.19/dlib/image_processing/detection_template_tools.h \
    dlib-19.19/dlib/image_processing/detection_template_tools_abstract.h \
    dlib-19.19/dlib/image_processing/frontal_face_detector.h \
    dlib-19.19/dlib/image_processing/frontal_face_detector_abstract.h \
    dlib-19.19/dlib/image_processing/full_object_detection.h \
    dlib-19.19/dlib/image_processing/full_object_detection_abstract.h \
    dlib-19.19/dlib/image_processing/generic_image.h \
    dlib-19.19/dlib/image_processing/object_detector.h \
    dlib-19.19/dlib/image_processing/object_detector_abstract.h \
    dlib-19.19/dlib/image_processing/remove_unobtainable_rectangles.h \
    dlib-19.19/dlib/image_processing/remove_unobtainable_rectangles_abstract.h \
    dlib-19.19/dlib/image_processing/render_face_detections.h \
    dlib-19.19/dlib/image_processing/render_face_detections_abstract.h \
    dlib-19.19/dlib/image_processing/scan_fhog_pyramid.h \
    dlib-19.19/dlib/image_processing/scan_fhog_pyramid_abstract.h \
    dlib-19.19/dlib/image_processing/scan_image.h \
    dlib-19.19/dlib/image_processing/scan_image_abstract.h \
    dlib-19.19/dlib/image_processing/scan_image_boxes.h \
    dlib-19.19/dlib/image_processing/scan_image_boxes_abstract.h \
    dlib-19.19/dlib/image_processing/scan_image_custom.h \
    dlib-19.19/dlib/image_processing/scan_image_custom_abstract.h \
    dlib-19.19/dlib/image_processing/scan_image_pyramid.h \
    dlib-19.19/dlib/image_processing/scan_image_pyramid_abstract.h \
    dlib-19.19/dlib/image_processing/scan_image_pyramid_tools.h \
    dlib-19.19/dlib/image_processing/scan_image_pyramid_tools_abstract.h \
    dlib-19.19/dlib/image_processing/setup_hashed_features.h \
    dlib-19.19/dlib/image_processing/setup_hashed_features_abstract.h \
    dlib-19.19/dlib/image_processing/shape_predictor.h \
    dlib-19.19/dlib/image_processing/shape_predictor_abstract.h \
    dlib-19.19/dlib/image_processing/shape_predictor_trainer.h \
    dlib-19.19/dlib/image_processing/shape_predictor_trainer_abstract.h \
    dlib-19.19/dlib/image_saver/dng_shared.h \
    dlib-19.19/dlib/image_saver/image_saver.h \
    dlib-19.19/dlib/image_saver/image_saver_abstract.h \
    dlib-19.19/dlib/image_saver/save_jpeg.h \
    dlib-19.19/dlib/image_saver/save_jpeg_abstract.h \
    dlib-19.19/dlib/image_saver/save_png.h \
    dlib-19.19/dlib/image_saver/save_png_abstract.h \
    dlib-19.19/dlib/image_transforms.h \
    dlib-19.19/dlib/image_transforms/assign_image.h \
    dlib-19.19/dlib/image_transforms/assign_image_abstract.h \
    dlib-19.19/dlib/image_transforms/colormaps.h \
    dlib-19.19/dlib/image_transforms/colormaps_abstract.h \
    dlib-19.19/dlib/image_transforms/draw.h \
    dlib-19.19/dlib/image_transforms/draw_abstract.h \
    dlib-19.19/dlib/image_transforms/edge_detector.h \
    dlib-19.19/dlib/image_transforms/edge_detector_abstract.h \
    dlib-19.19/dlib/image_transforms/equalize_histogram.h \
    dlib-19.19/dlib/image_transforms/equalize_histogram_abstract.h \
    dlib-19.19/dlib/image_transforms/fhog.h \
    dlib-19.19/dlib/image_transforms/fhog_abstract.h \
    dlib-19.19/dlib/image_transforms/hough_transform.h \
    dlib-19.19/dlib/image_transforms/hough_transform_abstract.h \
    dlib-19.19/dlib/image_transforms/image_pyramid.h \
    dlib-19.19/dlib/image_transforms/image_pyramid_abstract.h \
    dlib-19.19/dlib/image_transforms/integral_image.h \
    dlib-19.19/dlib/image_transforms/integral_image_abstract.h \
    dlib-19.19/dlib/image_transforms/interpolation.h \
    dlib-19.19/dlib/image_transforms/interpolation_abstract.h \
    dlib-19.19/dlib/image_transforms/label_connected_blobs.h \
    dlib-19.19/dlib/image_transforms/label_connected_blobs_abstract.h \
    dlib-19.19/dlib/image_transforms/lbp.h \
    dlib-19.19/dlib/image_transforms/lbp_abstract.h \
    dlib-19.19/dlib/image_transforms/morphological_operations.h \
    dlib-19.19/dlib/image_transforms/morphological_operations_abstract.h \
    dlib-19.19/dlib/image_transforms/random_color_transform.h \
    dlib-19.19/dlib/image_transforms/random_color_transform_abstract.h \
    dlib-19.19/dlib/image_transforms/random_cropper.h \
    dlib-19.19/dlib/image_transforms/random_cropper_abstract.h \
    dlib-19.19/dlib/image_transforms/segment_image.h \
    dlib-19.19/dlib/image_transforms/segment_image_abstract.h \
    dlib-19.19/dlib/image_transforms/spatial_filtering.h \
    dlib-19.19/dlib/image_transforms/spatial_filtering_abstract.h \
    dlib-19.19/dlib/image_transforms/thresholding.h \
    dlib-19.19/dlib/image_transforms/thresholding_abstract.h \
    dlib-19.19/dlib/interfaces/cmd_line_parser_option.h \
    dlib-19.19/dlib/interfaces/enumerable.h \
    dlib-19.19/dlib/interfaces/map_pair.h \
    dlib-19.19/dlib/interfaces/remover.h \
    dlib-19.19/dlib/iomanip \
    dlib-19.19/dlib/iosfwd \
    dlib-19.19/dlib/iosockstream.h \
    dlib-19.19/dlib/iosockstream/iosockstream.h \
    dlib-19.19/dlib/iosockstream/iosockstream_abstract.h \
    dlib-19.19/dlib/iostream \
    dlib-19.19/dlib/is_kind.h \
    dlib-19.19/dlib/istream \
    dlib-19.19/dlib/java/java_array.h \
    dlib-19.19/dlib/java/swig_api.h \
    dlib-19.19/dlib/linker.h \
    dlib-19.19/dlib/linker/linker_kernel_1.h \
    dlib-19.19/dlib/linker/linker_kernel_abstract.h \
    dlib-19.19/dlib/locale \
    dlib-19.19/dlib/logger.h \
    dlib-19.19/dlib/logger/extra_logger_headers.h \
    dlib-19.19/dlib/logger/logger_config_file.h \
    dlib-19.19/dlib/logger/logger_kernel_1.h \
    dlib-19.19/dlib/logger/logger_kernel_abstract.h \
    dlib-19.19/dlib/lsh.h \
    dlib-19.19/dlib/lsh/create_random_projection_hash.h \
    dlib-19.19/dlib/lsh/create_random_projection_hash_abstract.h \
    dlib-19.19/dlib/lsh/hashes.h \
    dlib-19.19/dlib/lsh/hashes_abstract.h \
    dlib-19.19/dlib/lsh/projection_hash.h \
    dlib-19.19/dlib/lsh/projection_hash_abstract.h \
    dlib-19.19/dlib/lz77_buffer.h \
    dlib-19.19/dlib/lz77_buffer/lz77_buffer_kernel_1.h \
    dlib-19.19/dlib/lz77_buffer/lz77_buffer_kernel_2.h \
    dlib-19.19/dlib/lz77_buffer/lz77_buffer_kernel_abstract.h \
    dlib-19.19/dlib/lz77_buffer/lz77_buffer_kernel_c.h \
    dlib-19.19/dlib/lzp_buffer.h \
    dlib-19.19/dlib/lzp_buffer/lzp_buffer_kernel_1.h \
    dlib-19.19/dlib/lzp_buffer/lzp_buffer_kernel_2.h \
    dlib-19.19/dlib/lzp_buffer/lzp_buffer_kernel_abstract.h \
    dlib-19.19/dlib/lzp_buffer/lzp_buffer_kernel_c.h \
    dlib-19.19/dlib/manifold_regularization.h \
    dlib-19.19/dlib/manifold_regularization/linear_manifold_regularizer.h \
    dlib-19.19/dlib/manifold_regularization/linear_manifold_regularizer_abstract.h \
    dlib-19.19/dlib/map.h \
    dlib-19.19/dlib/map/map_kernel_1.h \
    dlib-19.19/dlib/map/map_kernel_abstract.h \
    dlib-19.19/dlib/map/map_kernel_c.h \
    dlib-19.19/dlib/matlab/call_matlab.h \
    dlib-19.19/dlib/matlab/subprocess_stream.h \
    dlib-19.19/dlib/matrix.h \
    dlib-19.19/dlib/matrix/cblas_constants.h \
    dlib-19.19/dlib/matrix/lapack/fortran_id.h \
    dlib-19.19/dlib/matrix/lapack/gees.h \
    dlib-19.19/dlib/matrix/lapack/geev.h \
    dlib-19.19/dlib/matrix/lapack/geqrf.h \
    dlib-19.19/dlib/matrix/lapack/gesdd.h \
    dlib-19.19/dlib/matrix/lapack/gesvd.h \
    dlib-19.19/dlib/matrix/lapack/getrf.h \
    dlib-19.19/dlib/matrix/lapack/ormqr.h \
    dlib-19.19/dlib/matrix/lapack/pbtrf.h \
    dlib-19.19/dlib/matrix/lapack/potrf.h \
    dlib-19.19/dlib/matrix/lapack/syev.h \
    dlib-19.19/dlib/matrix/lapack/syevr.h \
    dlib-19.19/dlib/matrix/matrix.h \
    dlib-19.19/dlib/matrix/matrix_abstract.h \
    dlib-19.19/dlib/matrix/matrix_assign.h \
    dlib-19.19/dlib/matrix/matrix_assign_fwd.h \
    dlib-19.19/dlib/matrix/matrix_blas_bindings.h \
    dlib-19.19/dlib/matrix/matrix_cholesky.h \
    dlib-19.19/dlib/matrix/matrix_conj_trans.h \
    dlib-19.19/dlib/matrix/matrix_conv.h \
    dlib-19.19/dlib/matrix/matrix_conv_abstract.h \
    dlib-19.19/dlib/matrix/matrix_data_layout.h \
    dlib-19.19/dlib/matrix/matrix_data_layout_abstract.h \
    dlib-19.19/dlib/matrix/matrix_default_mul.h \
    dlib-19.19/dlib/matrix/matrix_eigenvalue.h \
    dlib-19.19/dlib/matrix/matrix_exp.h \
    dlib-19.19/dlib/matrix/matrix_exp_abstract.h \
    dlib-19.19/dlib/matrix/matrix_expressions.h \
    dlib-19.19/dlib/matrix/matrix_fft.h \
    dlib-19.19/dlib/matrix/matrix_fft_abstract.h \
    dlib-19.19/dlib/matrix/matrix_fwd.h \
    dlib-19.19/dlib/matrix/matrix_generic_image.h \
    dlib-19.19/dlib/matrix/matrix_la.h \
    dlib-19.19/dlib/matrix/matrix_la_abstract.h \
    dlib-19.19/dlib/matrix/matrix_lu.h \
    dlib-19.19/dlib/matrix/matrix_mat.h \
    dlib-19.19/dlib/matrix/matrix_mat_abstract.h \
    dlib-19.19/dlib/matrix/matrix_math_functions.h \
    dlib-19.19/dlib/matrix/matrix_math_functions_abstract.h \
    dlib-19.19/dlib/matrix/matrix_op.h \
    dlib-19.19/dlib/matrix/matrix_qr.h \
    dlib-19.19/dlib/matrix/matrix_read_from_istream.h \
    dlib-19.19/dlib/matrix/matrix_subexp.h \
    dlib-19.19/dlib/matrix/matrix_subexp_abstract.h \
    dlib-19.19/dlib/matrix/matrix_trsm.h \
    dlib-19.19/dlib/matrix/matrix_utilities.h \
    dlib-19.19/dlib/matrix/matrix_utilities_abstract.h \
    dlib-19.19/dlib/matrix/symmetric_matrix_cache.h \
    dlib-19.19/dlib/matrix/symmetric_matrix_cache_abstract.h \
    dlib-19.19/dlib/md5.h \
    dlib-19.19/dlib/md5/md5_kernel_1.h \
    dlib-19.19/dlib/md5/md5_kernel_abstract.h \
    dlib-19.19/dlib/member_function_pointer.h \
    dlib-19.19/dlib/member_function_pointer/make_mfp.h \
    dlib-19.19/dlib/member_function_pointer/make_mfp_abstract.h \
    dlib-19.19/dlib/member_function_pointer/member_function_pointer_kernel_1.h \
    dlib-19.19/dlib/member_function_pointer/member_function_pointer_kernel_abstract.h \
    dlib-19.19/dlib/memory_manager.h \
    dlib-19.19/dlib/memory_manager/memory_manager_kernel_1.h \
    dlib-19.19/dlib/memory_manager/memory_manager_kernel_2.h \
    dlib-19.19/dlib/memory_manager/memory_manager_kernel_3.h \
    dlib-19.19/dlib/memory_manager/memory_manager_kernel_abstract.h \
    dlib-19.19/dlib/memory_manager_global.h \
    dlib-19.19/dlib/memory_manager_global/memory_manager_global_kernel_1.h \
    dlib-19.19/dlib/memory_manager_global/memory_manager_global_kernel_abstract.h \
    dlib-19.19/dlib/memory_manager_stateless.h \
    dlib-19.19/dlib/memory_manager_stateless/memory_manager_stateless_kernel_1.h \
    dlib-19.19/dlib/memory_manager_stateless/memory_manager_stateless_kernel_2.h \
    dlib-19.19/dlib/memory_manager_stateless/memory_manager_stateless_kernel_abstract.h \
    dlib-19.19/dlib/metaprogramming.h \
    dlib-19.19/dlib/misc_api.h \
    dlib-19.19/dlib/misc_api/misc_api_kernel_1.h \
    dlib-19.19/dlib/misc_api/misc_api_kernel_2.h \
    dlib-19.19/dlib/misc_api/misc_api_kernel_abstract.h \
    dlib-19.19/dlib/misc_api/misc_api_shared.h \
    dlib-19.19/dlib/misc_api/posix.h \
    dlib-19.19/dlib/misc_api/windows.h \
    dlib-19.19/dlib/mlp.h \
    dlib-19.19/dlib/mlp/mlp_kernel_1.h \
    dlib-19.19/dlib/mlp/mlp_kernel_abstract.h \
    dlib-19.19/dlib/mlp/mlp_kernel_c.h \
    dlib-19.19/dlib/noncopyable.h \
    dlib-19.19/dlib/numeric_constants.h \
    dlib-19.19/dlib/numerical_integration.h \
    dlib-19.19/dlib/numerical_integration/integrate_function_adapt_simpson.h \
    dlib-19.19/dlib/numerical_integration/integrate_function_adapt_simpson_abstract.h \
    dlib-19.19/dlib/opencv.h \
    dlib-19.19/dlib/opencv/cv_image.h \
    dlib-19.19/dlib/opencv/cv_image_abstract.h \
    dlib-19.19/dlib/opencv/to_open_cv.h \
    dlib-19.19/dlib/opencv/to_open_cv_abstract.h \
    dlib-19.19/dlib/optimization.h \
    dlib-19.19/dlib/optimization/elastic_net.h \
    dlib-19.19/dlib/optimization/elastic_net_abstract.h \
    dlib-19.19/dlib/optimization/find_max_factor_graph_nmplp.h \
    dlib-19.19/dlib/optimization/find_max_factor_graph_nmplp_abstract.h \
    dlib-19.19/dlib/optimization/find_max_factor_graph_viterbi.h \
    dlib-19.19/dlib/optimization/find_max_factor_graph_viterbi_abstract.h \
    dlib-19.19/dlib/optimization/find_max_parse_cky.h \
    dlib-19.19/dlib/optimization/find_max_parse_cky_abstract.h \
    dlib-19.19/dlib/optimization/find_optimal_parameters.h \
    dlib-19.19/dlib/optimization/find_optimal_parameters_abstract.h \
    dlib-19.19/dlib/optimization/isotonic_regression.h \
    dlib-19.19/dlib/optimization/isotonic_regression_abstract.h \
    dlib-19.19/dlib/optimization/max_cost_assignment.h \
    dlib-19.19/dlib/optimization/max_cost_assignment_abstract.h \
    dlib-19.19/dlib/optimization/max_sum_submatrix.h \
    dlib-19.19/dlib/optimization/max_sum_submatrix_abstract.h \
    dlib-19.19/dlib/optimization/optimization.h \
    dlib-19.19/dlib/optimization/optimization_abstract.h \
    dlib-19.19/dlib/optimization/optimization_bobyqa.h \
    dlib-19.19/dlib/optimization/optimization_bobyqa_abstract.h \
    dlib-19.19/dlib/optimization/optimization_least_squares.h \
    dlib-19.19/dlib/optimization/optimization_least_squares_abstract.h \
    dlib-19.19/dlib/optimization/optimization_line_search.h \
    dlib-19.19/dlib/optimization/optimization_line_search_abstract.h \
    dlib-19.19/dlib/optimization/optimization_oca.h \
    dlib-19.19/dlib/optimization/optimization_oca_abstract.h \
    dlib-19.19/dlib/optimization/optimization_search_strategies.h \
    dlib-19.19/dlib/optimization/optimization_search_strategies_abstract.h \
    dlib-19.19/dlib/optimization/optimization_solve_qp2_using_smo.h \
    dlib-19.19/dlib/optimization/optimization_solve_qp2_using_smo_abstract.h \
    dlib-19.19/dlib/optimization/optimization_solve_qp3_using_smo.h \
    dlib-19.19/dlib/optimization/optimization_solve_qp3_using_smo_abstract.h \
    dlib-19.19/dlib/optimization/optimization_solve_qp_using_smo.h \
    dlib-19.19/dlib/optimization/optimization_solve_qp_using_smo_abstract.h \
    dlib-19.19/dlib/optimization/optimization_stop_strategies.h \
    dlib-19.19/dlib/optimization/optimization_stop_strategies_abstract.h \
    dlib-19.19/dlib/optimization/optimization_trust_region.h \
    dlib-19.19/dlib/optimization/optimization_trust_region_abstract.h \
    dlib-19.19/dlib/ostream \
    dlib-19.19/dlib/pipe.h \
    dlib-19.19/dlib/pipe/pipe_kernel_1.h \
    dlib-19.19/dlib/pipe/pipe_kernel_abstract.h \
    dlib-19.19/dlib/pixel.h \
    dlib-19.19/dlib/platform.h \
    dlib-19.19/dlib/python.h \
    dlib-19.19/dlib/python/numpy_image.h \
    dlib-19.19/dlib/python/pyassert.h \
    dlib-19.19/dlib/python/pybind_utils.h \
    dlib-19.19/dlib/python/serialize_pickle.h \
    dlib-19.19/dlib/quantum_computing.h \
    dlib-19.19/dlib/quantum_computing/quantum_computing.h \
    dlib-19.19/dlib/quantum_computing/quantum_computing_abstract.h \
    dlib-19.19/dlib/queue.h \
    dlib-19.19/dlib/queue/queue_kernel_1.h \
    dlib-19.19/dlib/queue/queue_kernel_2.h \
    dlib-19.19/dlib/queue/queue_kernel_abstract.h \
    dlib-19.19/dlib/queue/queue_kernel_c.h \
    dlib-19.19/dlib/queue/queue_sort_1.h \
    dlib-19.19/dlib/queue/queue_sort_abstract.h \
    dlib-19.19/dlib/rand.h \
    dlib-19.19/dlib/rand/mersenne_twister.h \
    dlib-19.19/dlib/rand/rand_kernel_1.h \
    dlib-19.19/dlib/rand/rand_kernel_abstract.h \
    dlib-19.19/dlib/random_forest.h \
    dlib-19.19/dlib/random_forest/random_forest_regression.h \
    dlib-19.19/dlib/random_forest/random_forest_regression_abstract.h \
    dlib-19.19/dlib/ref.h \
    dlib-19.19/dlib/reference_counter.h \
    dlib-19.19/dlib/reference_counter/reference_counter_kernel_1.h \
    dlib-19.19/dlib/reference_counter/reference_counter_kernel_abstract.h \
    dlib-19.19/dlib/revision.h \
    dlib-19.19/dlib/revision.h.in \
    dlib-19.19/dlib/sequence.h \
    dlib-19.19/dlib/sequence/sequence_compare_1.h \
    dlib-19.19/dlib/sequence/sequence_compare_abstract.h \
    dlib-19.19/dlib/sequence/sequence_kernel_1.h \
    dlib-19.19/dlib/sequence/sequence_kernel_2.h \
    dlib-19.19/dlib/sequence/sequence_kernel_abstract.h \
    dlib-19.19/dlib/sequence/sequence_kernel_c.h \
    dlib-19.19/dlib/sequence/sequence_sort_1.h \
    dlib-19.19/dlib/sequence/sequence_sort_2.h \
    dlib-19.19/dlib/sequence/sequence_sort_abstract.h \
    dlib-19.19/dlib/serialize.h \
    dlib-19.19/dlib/server.h \
    dlib-19.19/dlib/server/server_http.h \
    dlib-19.19/dlib/server/server_http_abstract.h \
    dlib-19.19/dlib/server/server_iostream.h \
    dlib-19.19/dlib/server/server_iostream_abstract.h \
    dlib-19.19/dlib/server/server_kernel.h \
    dlib-19.19/dlib/server/server_kernel_abstract.h \
    dlib-19.19/dlib/set.h \
    dlib-19.19/dlib/set/set_compare_1.h \
    dlib-19.19/dlib/set/set_compare_abstract.h \
    dlib-19.19/dlib/set/set_kernel_1.h \
    dlib-19.19/dlib/set/set_kernel_abstract.h \
    dlib-19.19/dlib/set/set_kernel_c.h \
    dlib-19.19/dlib/set_utils.h \
    dlib-19.19/dlib/set_utils/set_utils.h \
    dlib-19.19/dlib/set_utils/set_utils_abstract.h \
    dlib-19.19/dlib/simd.h \
    dlib-19.19/dlib/simd/simd4f.h \
    dlib-19.19/dlib/simd/simd4i.h \
    dlib-19.19/dlib/simd/simd8f.h \
    dlib-19.19/dlib/simd/simd8i.h \
    dlib-19.19/dlib/simd/simd_check.h \
    dlib-19.19/dlib/sliding_buffer.h \
    dlib-19.19/dlib/sliding_buffer/circular_buffer.h \
    dlib-19.19/dlib/sliding_buffer/circular_buffer_abstract.h \
    dlib-19.19/dlib/sliding_buffer/sliding_buffer_kernel_1.h \
    dlib-19.19/dlib/sliding_buffer/sliding_buffer_kernel_abstract.h \
    dlib-19.19/dlib/sliding_buffer/sliding_buffer_kernel_c.h \
    dlib-19.19/dlib/smart_pointers.h \
    dlib-19.19/dlib/smart_pointers/scoped_ptr.h \
    dlib-19.19/dlib/smart_pointers/shared_ptr.h \
    dlib-19.19/dlib/smart_pointers/shared_ptr_abstract.h \
    dlib-19.19/dlib/smart_pointers/shared_ptr_thread_safe.h \
    dlib-19.19/dlib/smart_pointers/shared_ptr_thread_safe_abstract.h \
    dlib-19.19/dlib/smart_pointers/weak_ptr.h \
    dlib-19.19/dlib/smart_pointers/weak_ptr_abstract.h \
    dlib-19.19/dlib/smart_pointers_thread_safe.h \
    dlib-19.19/dlib/sockets.h \
    dlib-19.19/dlib/sockets/posix.h \
    dlib-19.19/dlib/sockets/sockets_extensions.h \
    dlib-19.19/dlib/sockets/sockets_extensions_abstract.h \
    dlib-19.19/dlib/sockets/sockets_kernel_1.h \
    dlib-19.19/dlib/sockets/sockets_kernel_2.h \
    dlib-19.19/dlib/sockets/sockets_kernel_abstract.h \
    dlib-19.19/dlib/sockets/windows.h \
    dlib-19.19/dlib/sockstreambuf.h \
    dlib-19.19/dlib/sockstreambuf/sockstreambuf.h \
    dlib-19.19/dlib/sockstreambuf/sockstreambuf_abstract.h \
    dlib-19.19/dlib/sockstreambuf/sockstreambuf_unbuffered.h \
    dlib-19.19/dlib/sort.h \
    dlib-19.19/dlib/sparse_vector.h \
    dlib-19.19/dlib/sqlite.h \
    dlib-19.19/dlib/sqlite/sqlite.h \
    dlib-19.19/dlib/sqlite/sqlite_abstract.h \
    dlib-19.19/dlib/sqlite/sqlite_tools.h \
    dlib-19.19/dlib/sqlite/sqlite_tools_abstract.h \
    dlib-19.19/dlib/sstream \
    dlib-19.19/dlib/stack.h \
    dlib-19.19/dlib/stack/stack_kernel_1.h \
    dlib-19.19/dlib/stack/stack_kernel_abstract.h \
    dlib-19.19/dlib/stack/stack_kernel_c.h \
    dlib-19.19/dlib/stack_trace.h \
    dlib-19.19/dlib/static_map.h \
    dlib-19.19/dlib/static_map/static_map_kernel_1.h \
    dlib-19.19/dlib/static_map/static_map_kernel_abstract.h \
    dlib-19.19/dlib/static_map/static_map_kernel_c.h \
    dlib-19.19/dlib/static_set.h \
    dlib-19.19/dlib/static_set/static_set_compare_1.h \
    dlib-19.19/dlib/static_set/static_set_compare_abstract.h \
    dlib-19.19/dlib/static_set/static_set_kernel_1.h \
    dlib-19.19/dlib/static_set/static_set_kernel_abstract.h \
    dlib-19.19/dlib/static_set/static_set_kernel_c.h \
    dlib-19.19/dlib/statistics.h \
    dlib-19.19/dlib/statistics/average_precision.h \
    dlib-19.19/dlib/statistics/average_precision_abstract.h \
    dlib-19.19/dlib/statistics/cca.h \
    dlib-19.19/dlib/statistics/cca_abstract.h \
    dlib-19.19/dlib/statistics/dpca.h \
    dlib-19.19/dlib/statistics/dpca_abstract.h \
    dlib-19.19/dlib/statistics/image_feature_sampling.h \
    dlib-19.19/dlib/statistics/image_feature_sampling_abstract.h \
    dlib-19.19/dlib/statistics/lda.h \
    dlib-19.19/dlib/statistics/lda_abstract.h \
    dlib-19.19/dlib/statistics/random_subset_selector.h \
    dlib-19.19/dlib/statistics/random_subset_selector_abstract.h \
    dlib-19.19/dlib/statistics/running_gradient.h \
    dlib-19.19/dlib/statistics/running_gradient_abstract.h \
    dlib-19.19/dlib/statistics/sammon.h \
    dlib-19.19/dlib/statistics/sammon_abstract.h \
    dlib-19.19/dlib/statistics/statistics.h \
    dlib-19.19/dlib/statistics/statistics_abstract.h \
    dlib-19.19/dlib/statistics/vector_normalizer_frobmetric.h \
    dlib-19.19/dlib/statistics/vector_normalizer_frobmetric_abstract.h \
    dlib-19.19/dlib/std_allocator.h \
    dlib-19.19/dlib/stl_checked.h \
    dlib-19.19/dlib/stl_checked/std_vector_c.h \
    dlib-19.19/dlib/stl_checked/std_vector_c_abstract.h \
    dlib-19.19/dlib/string.h \
    dlib-19.19/dlib/string/cassert \
    dlib-19.19/dlib/string/iomanip \
    dlib-19.19/dlib/string/iosfwd \
    dlib-19.19/dlib/string/iostream \
    dlib-19.19/dlib/string/locale \
    dlib-19.19/dlib/string/string.h \
    dlib-19.19/dlib/string/string_abstract.h \
    dlib-19.19/dlib/svm.h \
    dlib-19.19/dlib/svm/active_learning.h \
    dlib-19.19/dlib/svm/active_learning_abstract.h \
    dlib-19.19/dlib/svm/assignment_function.h \
    dlib-19.19/dlib/svm/assignment_function_abstract.h \
    dlib-19.19/dlib/svm/auto.h \
    dlib-19.19/dlib/svm/auto_abstract.h \
    dlib-19.19/dlib/svm/cross_validate_assignment_trainer.h \
    dlib-19.19/dlib/svm/cross_validate_assignment_trainer_abstract.h \
    dlib-19.19/dlib/svm/cross_validate_graph_labeling_trainer.h \
    dlib-19.19/dlib/svm/cross_validate_graph_labeling_trainer_abstract.h \
    dlib-19.19/dlib/svm/cross_validate_multiclass_trainer.h \
    dlib-19.19/dlib/svm/cross_validate_multiclass_trainer_abstract.h \
    dlib-19.19/dlib/svm/cross_validate_object_detection_trainer.h \
    dlib-19.19/dlib/svm/cross_validate_object_detection_trainer_abstract.h \
    dlib-19.19/dlib/svm/cross_validate_regression_trainer.h \
    dlib-19.19/dlib/svm/cross_validate_regression_trainer_abstract.h \
    dlib-19.19/dlib/svm/cross_validate_sequence_labeler.h \
    dlib-19.19/dlib/svm/cross_validate_sequence_labeler_abstract.h \
    dlib-19.19/dlib/svm/cross_validate_sequence_segmenter.h \
    dlib-19.19/dlib/svm/cross_validate_sequence_segmenter_abstract.h \
    dlib-19.19/dlib/svm/cross_validate_track_association_trainer.h \
    dlib-19.19/dlib/svm/cross_validate_track_association_trainer_abstract.h \
    dlib-19.19/dlib/svm/empirical_kernel_map.h \
    dlib-19.19/dlib/svm/empirical_kernel_map_abstract.h \
    dlib-19.19/dlib/svm/feature_ranking.h \
    dlib-19.19/dlib/svm/feature_ranking_abstract.h \
    dlib-19.19/dlib/svm/function.h \
    dlib-19.19/dlib/svm/function_abstract.h \
    dlib-19.19/dlib/svm/kcentroid.h \
    dlib-19.19/dlib/svm/kcentroid_abstract.h \
    dlib-19.19/dlib/svm/kcentroid_overloads.h \
    dlib-19.19/dlib/svm/kernel.h \
    dlib-19.19/dlib/svm/kernel_abstract.h \
    dlib-19.19/dlib/svm/kernel_matrix.h \
    dlib-19.19/dlib/svm/kernel_matrix_abstract.h \
    dlib-19.19/dlib/svm/kkmeans.h \
    dlib-19.19/dlib/svm/kkmeans_abstract.h \
    dlib-19.19/dlib/svm/krls.h \
    dlib-19.19/dlib/svm/krls_abstract.h \
    dlib-19.19/dlib/svm/krr_trainer.h \
    dlib-19.19/dlib/svm/krr_trainer_abstract.h \
    dlib-19.19/dlib/svm/linearly_independent_subset_finder.h \
    dlib-19.19/dlib/svm/linearly_independent_subset_finder_abstract.h \
    dlib-19.19/dlib/svm/multiclass_tools.h \
    dlib-19.19/dlib/svm/multiclass_tools_abstract.h \
    dlib-19.19/dlib/svm/null_df.h \
    dlib-19.19/dlib/svm/null_trainer.h \
    dlib-19.19/dlib/svm/null_trainer_abstract.h \
    dlib-19.19/dlib/svm/num_nonnegative_weights.h \
    dlib-19.19/dlib/svm/one_vs_all_decision_function.h \
    dlib-19.19/dlib/svm/one_vs_all_decision_function_abstract.h \
    dlib-19.19/dlib/svm/one_vs_all_trainer.h \
    dlib-19.19/dlib/svm/one_vs_all_trainer_abstract.h \
    dlib-19.19/dlib/svm/one_vs_one_decision_function.h \
    dlib-19.19/dlib/svm/one_vs_one_decision_function_abstract.h \
    dlib-19.19/dlib/svm/one_vs_one_trainer.h \
    dlib-19.19/dlib/svm/one_vs_one_trainer_abstract.h \
    dlib-19.19/dlib/svm/pegasos.h \
    dlib-19.19/dlib/svm/pegasos_abstract.h \
    dlib-19.19/dlib/svm/ranking_tools.h \
    dlib-19.19/dlib/svm/ranking_tools_abstract.h \
    dlib-19.19/dlib/svm/rbf_network.h \
    dlib-19.19/dlib/svm/rbf_network_abstract.h \
    dlib-19.19/dlib/svm/reduced.h \
    dlib-19.19/dlib/svm/reduced_abstract.h \
    dlib-19.19/dlib/svm/rls.h \
    dlib-19.19/dlib/svm/rls_abstract.h \
    dlib-19.19/dlib/svm/roc_trainer.h \
    dlib-19.19/dlib/svm/roc_trainer_abstract.h \
    dlib-19.19/dlib/svm/rr_trainer.h \
    dlib-19.19/dlib/svm/rr_trainer_abstract.h \
    dlib-19.19/dlib/svm/rvm.h \
    dlib-19.19/dlib/svm/rvm_abstract.h \
    dlib-19.19/dlib/svm/sequence_labeler.h \
    dlib-19.19/dlib/svm/sequence_labeler_abstract.h \
    dlib-19.19/dlib/svm/sequence_segmenter.h \
    dlib-19.19/dlib/svm/sequence_segmenter_abstract.h \
    dlib-19.19/dlib/svm/simplify_linear_decision_function.h \
    dlib-19.19/dlib/svm/simplify_linear_decision_function_abstract.h \
    dlib-19.19/dlib/svm/sort_basis_vectors.h \
    dlib-19.19/dlib/svm/sort_basis_vectors_abstract.h \
    dlib-19.19/dlib/svm/sparse_kernel.h \
    dlib-19.19/dlib/svm/sparse_kernel_abstract.h \
    dlib-19.19/dlib/svm/sparse_vector.h \
    dlib-19.19/dlib/svm/sparse_vector_abstract.h \
    dlib-19.19/dlib/svm/structural_assignment_trainer.h \
    dlib-19.19/dlib/svm/structural_assignment_trainer_abstract.h \
    dlib-19.19/dlib/svm/structural_graph_labeling_trainer.h \
    dlib-19.19/dlib/svm/structural_graph_labeling_trainer_abstract.h \
    dlib-19.19/dlib/svm/structural_object_detection_trainer.h \
    dlib-19.19/dlib/svm/structural_object_detection_trainer_abstract.h \
    dlib-19.19/dlib/svm/structural_sequence_labeling_trainer.h \
    dlib-19.19/dlib/svm/structural_sequence_labeling_trainer_abstract.h \
    dlib-19.19/dlib/svm/structural_sequence_segmentation_trainer.h \
    dlib-19.19/dlib/svm/structural_sequence_segmentation_trainer_abstract.h \
    dlib-19.19/dlib/svm/structural_svm_assignment_problem.h \
    dlib-19.19/dlib/svm/structural_svm_assignment_problem_abstract.h \
    dlib-19.19/dlib/svm/structural_svm_distributed.h \
    dlib-19.19/dlib/svm/structural_svm_distributed_abstract.h \
    dlib-19.19/dlib/svm/structural_svm_graph_labeling_problem.h \
    dlib-19.19/dlib/svm/structural_svm_graph_labeling_problem_abstract.h \
    dlib-19.19/dlib/svm/structural_svm_object_detection_problem.h \
    dlib-19.19/dlib/svm/structural_svm_object_detection_problem_abstract.h \
    dlib-19.19/dlib/svm/structural_svm_problem.h \
    dlib-19.19/dlib/svm/structural_svm_problem_abstract.h \
    dlib-19.19/dlib/svm/structural_svm_problem_threaded.h \
    dlib-19.19/dlib/svm/structural_svm_problem_threaded_abstract.h \
    dlib-19.19/dlib/svm/structural_svm_sequence_labeling_problem.h \
    dlib-19.19/dlib/svm/structural_svm_sequence_labeling_problem_abstract.h \
    dlib-19.19/dlib/svm/structural_track_association_trainer.h \
    dlib-19.19/dlib/svm/structural_track_association_trainer_abstract.h \
    dlib-19.19/dlib/svm/svm.h \
    dlib-19.19/dlib/svm/svm_abstract.h \
    dlib-19.19/dlib/svm/svm_c_ekm_trainer.h \
    dlib-19.19/dlib/svm/svm_c_ekm_trainer_abstract.h \
    dlib-19.19/dlib/svm/svm_c_linear_dcd_trainer.h \
    dlib-19.19/dlib/svm/svm_c_linear_dcd_trainer_abstract.h \
    dlib-19.19/dlib/svm/svm_c_linear_trainer.h \
    dlib-19.19/dlib/svm/svm_c_linear_trainer_abstract.h \
    dlib-19.19/dlib/svm/svm_c_trainer.h \
    dlib-19.19/dlib/svm/svm_c_trainer_abstract.h \
    dlib-19.19/dlib/svm/svm_multiclass_linear_trainer.h \
    dlib-19.19/dlib/svm/svm_multiclass_linear_trainer_abstract.h \
    dlib-19.19/dlib/svm/svm_nu_trainer.h \
    dlib-19.19/dlib/svm/svm_nu_trainer_abstract.h \
    dlib-19.19/dlib/svm/svm_one_class_trainer.h \
    dlib-19.19/dlib/svm/svm_one_class_trainer_abstract.h \
    dlib-19.19/dlib/svm/svm_rank_trainer.h \
    dlib-19.19/dlib/svm/svm_rank_trainer_abstract.h \
    dlib-19.19/dlib/svm/svm_threaded.h \
    dlib-19.19/dlib/svm/svm_threaded_abstract.h \
    dlib-19.19/dlib/svm/svr_linear_trainer.h \
    dlib-19.19/dlib/svm/svr_linear_trainer_abstract.h \
    dlib-19.19/dlib/svm/svr_trainer.h \
    dlib-19.19/dlib/svm/svr_trainer_abstract.h \
    dlib-19.19/dlib/svm/track_association_function.h \
    dlib-19.19/dlib/svm/track_association_function_abstract.h \
    dlib-19.19/dlib/svm_threaded.h \
    dlib-19.19/dlib/sync_extension.h \
    dlib-19.19/dlib/sync_extension/sync_extension_kernel_1.h \
    dlib-19.19/dlib/sync_extension/sync_extension_kernel_abstract.h \
    dlib-19.19/dlib/test/binary_search_tree.h \
    dlib-19.19/dlib/test/checkerboard.h \
    dlib-19.19/dlib/test/cmd_line_parser.h \
    dlib-19.19/dlib/test/conditioning_class.h \
    dlib-19.19/dlib/test/create_iris_datafile.h \
    dlib-19.19/dlib/test/optimization_test_functions.h \
    dlib-19.19/dlib/test/tester.h \
    dlib-19.19/dlib/test_for_odr_violations.h \
    dlib-19.19/dlib/threads.h \
    dlib-19.19/dlib/threads/async.h \
    dlib-19.19/dlib/threads/async_abstract.h \
    dlib-19.19/dlib/threads/auto_mutex_extension.h \
    dlib-19.19/dlib/threads/auto_mutex_extension_abstract.h \
    dlib-19.19/dlib/threads/auto_unlock_extension.h \
    dlib-19.19/dlib/threads/auto_unlock_extension_abstract.h \
    dlib-19.19/dlib/threads/create_new_thread_extension.h \
    dlib-19.19/dlib/threads/create_new_thread_extension_abstract.h \
    dlib-19.19/dlib/threads/multithreaded_object_extension.h \
    dlib-19.19/dlib/threads/multithreaded_object_extension_abstract.h \
    dlib-19.19/dlib/threads/parallel_for_extension.h \
    dlib-19.19/dlib/threads/parallel_for_extension_abstract.h \
    dlib-19.19/dlib/threads/posix.h \
    dlib-19.19/dlib/threads/read_write_mutex_extension.h \
    dlib-19.19/dlib/threads/read_write_mutex_extension_abstract.h \
    dlib-19.19/dlib/threads/rmutex_extension.h \
    dlib-19.19/dlib/threads/rmutex_extension_abstract.h \
    dlib-19.19/dlib/threads/rsignaler_extension.h \
    dlib-19.19/dlib/threads/rsignaler_extension_abstract.h \
    dlib-19.19/dlib/threads/thread_function_extension.h \
    dlib-19.19/dlib/threads/thread_function_extension_abstract.h \
    dlib-19.19/dlib/threads/thread_pool_extension.h \
    dlib-19.19/dlib/threads/thread_pool_extension_abstract.h \
    dlib-19.19/dlib/threads/thread_specific_data_extension.h \
    dlib-19.19/dlib/threads/thread_specific_data_extension_abstract.h \
    dlib-19.19/dlib/threads/threaded_object_extension.h \
    dlib-19.19/dlib/threads/threaded_object_extension_abstract.h \
    dlib-19.19/dlib/threads/threads_kernel.h \
    dlib-19.19/dlib/threads/threads_kernel_1.h \
    dlib-19.19/dlib/threads/threads_kernel_2.h \
    dlib-19.19/dlib/threads/threads_kernel_abstract.h \
    dlib-19.19/dlib/threads/threads_kernel_shared.h \
    dlib-19.19/dlib/threads/windows.h \
    dlib-19.19/dlib/time_this.h \
    dlib-19.19/dlib/timeout.h \
    dlib-19.19/dlib/timeout/timeout.h \
    dlib-19.19/dlib/timeout/timeout_abstract.h \
    dlib-19.19/dlib/timer.h \
    dlib-19.19/dlib/timer/timer.h \
    dlib-19.19/dlib/timer/timer_abstract.h \
    dlib-19.19/dlib/timer/timer_heavy.h \
    dlib-19.19/dlib/timing.h \
    dlib-19.19/dlib/tokenizer.h \
    dlib-19.19/dlib/tokenizer/tokenizer_kernel_1.h \
    dlib-19.19/dlib/tokenizer/tokenizer_kernel_abstract.h \
    dlib-19.19/dlib/tokenizer/tokenizer_kernel_c.h \
    dlib-19.19/dlib/tuple.h \
    dlib-19.19/dlib/tuple/tuple.h \
    dlib-19.19/dlib/tuple/tuple_abstract.h \
    dlib-19.19/dlib/type_safe_union.h \
    dlib-19.19/dlib/type_safe_union/type_safe_union_kernel.h \
    dlib-19.19/dlib/type_safe_union/type_safe_union_kernel_abstract.h \
    dlib-19.19/dlib/uintn.h \
    dlib-19.19/dlib/unicode.h \
    dlib-19.19/dlib/unicode/unicode.h \
    dlib-19.19/dlib/unicode/unicode_abstract.h \
    dlib-19.19/dlib/unordered_pair.h \
    dlib-19.19/dlib/vectorstream.h \
    dlib-19.19/dlib/vectorstream/unserialize.h \
    dlib-19.19/dlib/vectorstream/unserialize_abstract.h \
    dlib-19.19/dlib/vectorstream/vectorstream.h \
    dlib-19.19/dlib/vectorstream/vectorstream_abstract.h \
    dlib-19.19/dlib/windows_magic.h \
    dlib-19.19/dlib/xml_parser.h \
    dlib-19.19/dlib/xml_parser/xml_parser_kernel_1.h \
    dlib-19.19/dlib/xml_parser/xml_parser_kernel_abstract.h \
    dlib-19.19/dlib/xml_parser/xml_parser_kernel_interfaces.h

DISTFILES += \ \
    dlib-19.19/dlib/CMakeLists.txt \
    dlib-19.19/dlib/LICENSE.txt \
    dlib-19.19/dlib/appveyor/dtest.yml \
    dlib-19.19/dlib/appveyor/dtest_vc2017.yml \
    dlib-19.19/dlib/appveyor/examples.yml \
    dlib-19.19/dlib/appveyor/python.yml \
    dlib-19.19/dlib/cmake \
    dlib-19.19/dlib/cmake_utils/add_global_compiler_switch.cmake \
    dlib-19.19/dlib/cmake_utils/check_if_avx_instructions_executable_on_host.cmake \
    dlib-19.19/dlib/cmake_utils/check_if_neon_available.cmake \
    dlib-19.19/dlib/cmake_utils/check_if_sse4_instructions_executable_on_host.cmake \
    dlib-19.19/dlib/cmake_utils/dlib.pc.in \
    dlib-19.19/dlib/cmake_utils/dlibConfig.cmake.in \
    dlib-19.19/dlib/cmake_utils/find_blas.cmake \
    dlib-19.19/dlib/cmake_utils/find_libjpeg.cmake \
    dlib-19.19/dlib/cmake_utils/find_libpng.cmake \
    dlib-19.19/dlib/cmake_utils/release_build_by_default \
    dlib-19.19/dlib/cmake_utils/set_compiler_specific_options.cmake \
    dlib-19.19/dlib/cmake_utils/tell_visual_studio_to_use_static_runtime.cmake \
    dlib-19.19/dlib/cmake_utils/test_for_avx/CMakeLists.txt \
    dlib-19.19/dlib/cmake_utils/test_for_cpp11/CMakeLists.txt \
    dlib-19.19/dlib/cmake_utils/test_for_cuda/CMakeLists.txt \
    dlib-19.19/dlib/cmake_utils/test_for_cuda/cuda_test.cu \
    dlib-19.19/dlib/cmake_utils/test_for_cudnn/CMakeLists.txt \
    dlib-19.19/dlib/cmake_utils/test_for_cudnn/find_cudnn.txt \
    dlib-19.19/dlib/cmake_utils/test_for_libjpeg/CMakeLists.txt \
    dlib-19.19/dlib/cmake_utils/test_for_libpng/CMakeLists.txt \
    dlib-19.19/dlib/cmake_utils/test_for_neon/CMakeLists.txt \
    dlib-19.19/dlib/cmake_utils/test_for_sse4/CMakeLists.txt \
    dlib-19.19/dlib/cmake_utils/use_cpp_11.cmake \
    dlib-19.19/dlib/config.h.in \
    dlib-19.19/dlib/cuda/cuda_dlib.cu \
    dlib-19.19/dlib/cuda/cusolver_dlibapi.cu \
    dlib-19.19/dlib/dlib_basic_cpp_build_tutorial.txt \
    dlib-19.19/dlib/dlib_include_path_tutorial.txt \
    dlib-19.19/dlib/external/cblas/CMakeLists.txt \
    dlib-19.19/dlib/external/cblas/README \
    dlib-19.19/dlib/external/cblas/cdotcsub.f \
    dlib-19.19/dlib/external/cblas/cdotusub.f \
    dlib-19.19/dlib/external/cblas/dasumsub.f \
    dlib-19.19/dlib/external/cblas/ddotsub.f \
    dlib-19.19/dlib/external/cblas/dnrm2sub.f \
    dlib-19.19/dlib/external/cblas/dsdotsub.f \
    dlib-19.19/dlib/external/cblas/dzasumsub.f \
    dlib-19.19/dlib/external/cblas/dznrm2sub.f \
    dlib-19.19/dlib/external/cblas/icamaxsub.f \
    dlib-19.19/dlib/external/cblas/idamaxsub.f \
    dlib-19.19/dlib/external/cblas/isamaxsub.f \
    dlib-19.19/dlib/external/cblas/izamaxsub.f \
    dlib-19.19/dlib/external/cblas/sasumsub.f \
    dlib-19.19/dlib/external/cblas/scasumsub.f \
    dlib-19.19/dlib/external/cblas/scnrm2sub.f \
    dlib-19.19/dlib/external/cblas/sdotsub.f \
    dlib-19.19/dlib/external/cblas/sdsdotsub.f \
    dlib-19.19/dlib/external/cblas/snrm2sub.f \
    dlib-19.19/dlib/external/cblas/zdotcsub.f \
    dlib-19.19/dlib/external/cblas/zdotusub.f \
    dlib-19.19/dlib/external/libjpeg/README \
    dlib-19.19/dlib/external/libjpeg/readme.dos \
    dlib-19.19/dlib/external/libpng/LICENSE \
    dlib-19.19/dlib/external/libpng/README \
    dlib-19.19/dlib/external/pybind11/CMakeLists.txt \
    dlib-19.19/dlib/external/pybind11/CONTRIBUTING.md \
    dlib-19.19/dlib/external/pybind11/LICENSE \
    dlib-19.19/dlib/external/pybind11/README.md \
    dlib-19.19/dlib/external/pybind11/tools/FindCatch.cmake \
    dlib-19.19/dlib/external/pybind11/tools/FindEigen3.cmake \
    dlib-19.19/dlib/external/pybind11/tools/FindPythonLibsNew.cmake \
    dlib-19.19/dlib/external/pybind11/tools/check-style.sh \
    dlib-19.19/dlib/external/pybind11/tools/libsize.py \
    dlib-19.19/dlib/external/pybind11/tools/mkdoc.py \
    dlib-19.19/dlib/external/pybind11/tools/pybind11Config.cmake.in \
    dlib-19.19/dlib/external/pybind11/tools/pybind11Tools.cmake \
    dlib-19.19/dlib/external/zlib/README \
    dlib-19.19/dlib/java/CMakeLists.txt \
    dlib-19.19/dlib/java/cmake_swig_jni \
    dlib-19.19/dlib/java/run_test.sh \
    dlib-19.19/dlib/java/swig_test.java \
    dlib-19.19/dlib/matlab/CMakeLists.txt \
    dlib-19.19/dlib/matlab/README.txt \
    dlib-19.19/dlib/matlab/cmake_mex_wrapper \
    dlib-19.19/dlib/matlab/example.m \
    dlib-19.19/dlib/test/CMakeLists.txt \
    dlib-19.19/dlib/test/WINDOWS_build_and_run_all_unit_tests.bat \
    dlib-19.19/dlib/test/blas_bindings/CMakeLists.txt \
    dlib-19.19/dlib/test/examples/CMakeLists.txt \
    dlib-19.19/dlib/test/gui/CMakeLists.txt \
    dlib-19.19/dlib/test/tools/CMakeLists.txt \
    dlib-19.19/dlib/travis/build-and-test.sh \
    dlib-19.19/dlib/travis/get-old-cmakes.sh

