#ifndef GLOBALFILE_H
#define GLOBALFILE_H

#define CAM_WIDTH 640
#define CAM_HEIGHT 480
#define FACE_DOWNSAMPLE_RATIO 2
#define SKIP_FRAMES 5
#define TWO_EYELID_ASPECT_RATIO_STANDARD 0.3
#define EAR_ASPECT_RATIO_STANDARD_LOW 0.8
#define EAR_ASPECT_RATIO_STANDARD_HIGH 1.25
#define MOUTH_ASPECT_RATIO_STANDARD  0.5
#define SHAPE_PREDIRTOR_68_FACE_LANDMARK "D:\\Projects\\GitProjects\\DoAnTotNghiep\\DoANTotNghiep\\dlib\\shape_predictor_68_face_landmarks.dat"

#endif // GLOBALFILE_H
