# CMake generated Testfile for 
# Source directory: E:/GitProiects/DoANTotNghiep/opencv/sources/modules/videoio
# Build directory: E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/videoio
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_videoio "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/bin/opencv_test_videoio.exe" "--gtest_output=xml:opencv_test_videoio.xml")
set_tests_properties(opencv_test_videoio PROPERTIES  LABELS "Main;opencv_videoio;Accuracy" WORKING_DIRECTORY "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/test-reports/accuracy" _BACKTRACE_TRIPLES "E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1309;ocv_add_test_from_target;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/videoio/CMakeLists.txt;191;ocv_add_accuracy_tests;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/videoio/CMakeLists.txt;0;")
add_test(opencv_perf_videoio "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/bin/opencv_perf_videoio.exe" "--gtest_output=xml:opencv_perf_videoio.xml")
set_tests_properties(opencv_perf_videoio PROPERTIES  LABELS "Main;opencv_videoio;Performance" WORKING_DIRECTORY "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/test-reports/performance" _BACKTRACE_TRIPLES "E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1211;ocv_add_test_from_target;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/videoio/CMakeLists.txt;192;ocv_add_perf_tests;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/videoio/CMakeLists.txt;0;")
add_test(opencv_sanity_videoio "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/bin/opencv_perf_videoio.exe" "--gtest_output=xml:opencv_perf_videoio.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_videoio PROPERTIES  LABELS "Main;opencv_videoio;Sanity" WORKING_DIRECTORY "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/test-reports/sanity" _BACKTRACE_TRIPLES "E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1212;ocv_add_test_from_target;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/videoio/CMakeLists.txt;192;ocv_add_perf_tests;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/videoio/CMakeLists.txt;0;")
