# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QIcon # import function cho

class MainScreen(QWidget):
    def __init__(self):
        super(MainScreen, self).__init__()
        self.ui = Ui_MainWindow() 				   # tạo một GUI với đối tượng là giao diện MlabDemo đã thiết kế
        self.ui.setupUi(self)
        self.setWindowTitle('BrainDetect')   # đặt tiêu đề cho giao diện 
        self.setWindowIcon(QIcon("BrainDetect.ico")) # tải icon cho giao diện 
        self.center()						   # hàm center() giúp đưa giao diện vào giữa màn hình 

    def center(self):	# định nghĩa hàm center() 
        qr = self.frameGeometry()  # nhận một cửa sổ hình chữ nhật mô tả màn hình chính của giao diện
        cp = QDesktopWidget().availableGeometry().center() # tính toán độ phân giải và tìm ra điểm giữa của màn hình
        qr.moveCenter(cp) # di chuyển điểm giữa của hình chữ nhật tới trùng với điểm giữa của màn hình, 
                            # giữ cho kích thước hình chữ nhật không đổi
        self.move(qr.topLeft()) # di chuyển màn hình chính của giao diện tới vị trí cửa sổ hình chữ nhật (ở giữa màn hình)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1331, 782)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(480, 720, 381, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pushButton_Back = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Back.sizePolicy().hasHeightForWidth())
        self.pushButton_Back.setSizePolicy(sizePolicy)
        self.pushButton_Back.setMinimumSize(QtCore.QSize(60, 40))
        self.pushButton_Back.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.hboxlayout.addWidget(self.pushButton_Back)
        self.pushButton_segmentation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_segmentation.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segmentation.sizePolicy().hasHeightForWidth())
        self.pushButton_segmentation.setSizePolicy(sizePolicy)
        self.pushButton_segmentation.setMaximumSize(QtCore.QSize(120, 40))
        self.pushButton_segmentation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_segmentation.setObjectName("pushButton_segmentation")
        self.hboxlayout.addWidget(self.pushButton_segmentation)
        self.pushButton_Next = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Next.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.hboxlayout.addWidget(self.pushButton_Next)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1331, 711))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_Prediction_All = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_Prediction_All.setObjectName("graphicsView_Prediction_All")
        self.gridLayout.addWidget(self.graphicsView_Prediction_All, 2, 1, 1, 1)
        self.graphicsView__Prediction_Core = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView__Prediction_Core.setObjectName("graphicsView__Prediction_Core")
        self.gridLayout.addWidget(self.graphicsView__Prediction_Core, 1, 1, 1, 1)
        self.graphicsView__Prediction_ET = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView__Prediction_ET.setObjectName("graphicsView__Prediction_ET")
        self.gridLayout.addWidget(self.graphicsView__Prediction_ET, 2, 0, 1, 1)
        self.graphicsView_Base = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView_Base.setObjectName("graphicsView_Base")
        self.gridLayout.addWidget(self.graphicsView_Base, 1, 0, 1, 1)
       # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Back.setText(_translate("MainWindow", "Back"))
        self.pushButton_segmentation.setText(_translate("MainWindow", "Segmentation Image"))
        self.pushButton_Next.setText(_translate("MainWindow", "Next"))
        #self.pushButton_Next.clicked.connect(QCoreApplication.instance().quit) # khi close được nhấn, dừng chương trình. 
