# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys 
from PyQt5.QtWidgets import *

class MainScreen(QWidget):
    def __init__(self):
        super(MainScreen, self).__init__()
        self.ui = Ui_MainWindow() 				   # tạo một GUI với đối tượng là giao diện MlabDemo đã thiết kế
        self.ui.setupUi(self)
        self.setWindowTitle('Brain Detect Using DNN')   # đặt tiêu đề cho giao diện 
        self.center()						   # hàm center() giúp đưa giao diện vào giữa màn hình 

    def center(self):	# định nghĩa hàm center() 
        qr = self.frameGeometry()  # nhận một cửa sổ hình chữ nhật mô tả màn hình chính của giao diện
        cp = QDesktopWidget().availableGeometry().center() # tính toán độ phân giải và tìm ra điểm giữa của màn hình
        qr.moveCenter(cp) # di chuyển điểm giữa của hình chữ nhật tới trùng với điểm giữa của màn hình, 
                            # giữ cho kích thước hình chữ nhật không đổi
        self.move(qr.topLeft()) # di chuyển màn hình chính của giao diện tới vị trí cửa sổ hình chữ nhật (ở giữa màn hình)	
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1333, 247)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(450, 170, 381, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pushButton_segmentation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_segmentation.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_segmentation.sizePolicy().hasHeightForWidth())
        self.pushButton_segmentation.setSizePolicy(sizePolicy)
        self.pushButton_segmentation.setMaximumSize(QtCore.QSize(120, 40))
        self.pushButton_segmentation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_segmentation.setObjectName("pushButton_segmentation")
        self.hboxlayout.addWidget(self.pushButton_segmentation)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 10, 1301, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_FolerPath = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_FolerPath.setObjectName("label_FolerPath")
        self.horizontalLayout.addWidget(self.label_FolerPath)
        self.lineEdit_FolderPath = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_FolderPath.setObjectName("lineEdit_FolderPath")
        self.horizontalLayout.addWidget(self.lineEdit_FolderPath)
        self.pushButton_OpenFileBroswer = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_OpenFileBroswer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_OpenFileBroswer.sizePolicy().hasHeightForWidth())
        self.pushButton_OpenFileBroswer.setSizePolicy(sizePolicy)
        self.pushButton_OpenFileBroswer.setMinimumSize(QtCore.QSize(20, 30))
        self.pushButton_OpenFileBroswer.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButton_OpenFileBroswer.setBaseSize(QtCore.QSize(100, 30))
        self.pushButton_OpenFileBroswer.setObjectName("pushButton_OpenFileBroswer")
        self.horizontalLayout.addWidget(self.pushButton_OpenFileBroswer)
        self.label_NotifyStatus = QtWidgets.QLabel(self.centralwidget)
        self.label_NotifyStatus.setGeometry(QtCore.QRect(20, 80, 1181, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_NotifyStatus.setFont(font)
        self.label_NotifyStatus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_NotifyStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NotifyStatus.setObjectName("label_NotifyStatus")
#        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_segmentation.setText(_translate("MainWindow", "Segmentation Image"))
        self.label_FolerPath.setText(_translate("MainWindow", "Folder path :"))
        self.lineEdit_FolderPath.setText(_translate("MainWindow", "Type image Path in here"))
        self.lineEdit_FolderPath.text()
        self.pushButton_OpenFileBroswer.setText(_translate("MainWindow", "....."))
        self.label_NotifyStatus.setText(_translate("MainWindow", "While training data, please wait until finished"))
