# CMake generated Testfile for 
# Source directory: E:/GitProiects/DoANTotNghiep/opencv/sources/modules/dnn
# Build directory: E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/modules/dnn
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_dnn "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/bin/opencv_test_dnn.exe" "--gtest_output=xml:opencv_test_dnn.xml")
set_tests_properties(opencv_test_dnn PROPERTIES  LABELS "Main;opencv_dnn;Accuracy" WORKING_DIRECTORY "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/test-reports/accuracy" _BACKTRACE_TRIPLES "E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1309;ocv_add_test_from_target;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/dnn/CMakeLists.txt;148;ocv_add_accuracy_tests;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/dnn/CMakeLists.txt;0;")
add_test(opencv_perf_dnn "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/bin/opencv_perf_dnn.exe" "--gtest_output=xml:opencv_perf_dnn.xml")
set_tests_properties(opencv_perf_dnn PROPERTIES  LABELS "Main;opencv_dnn;Performance" WORKING_DIRECTORY "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/test-reports/performance" _BACKTRACE_TRIPLES "E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1211;ocv_add_test_from_target;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/dnn/CMakeLists.txt;153;ocv_add_perf_tests;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/dnn/CMakeLists.txt;0;")
add_test(opencv_sanity_dnn "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/bin/opencv_perf_dnn.exe" "--gtest_output=xml:opencv_perf_dnn.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_dnn PROPERTIES  LABELS "Main;opencv_dnn;Sanity" WORKING_DIRECTORY "E:/GitProiects/DoANTotNghiep/opencv/build_Mingw32/test-reports/sanity" _BACKTRACE_TRIPLES "E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVUtils.cmake;1640;add_test;E:/GitProiects/DoANTotNghiep/opencv/sources/cmake/OpenCVModule.cmake;1212;ocv_add_test_from_target;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/dnn/CMakeLists.txt;153;ocv_add_perf_tests;E:/GitProiects/DoANTotNghiep/opencv/sources/modules/dnn/CMakeLists.txt;0;")
